/* Linux command database — part 1 of 2 (files, text, system, process) */
window.CMDS = (window.CMDS || []).concat([

  /* ---------------- Files & Directories ---------------- */
  { name: "ls", cat: "files", desc: "List directory contents.", usage: "ls [options] [path...]", examples: ["ls -la", "ls -lhS", "ls -R /etc"] },
  { name: "cd", cat: "files", desc: "Change the current working directory.", usage: "cd [directory]", examples: ["cd /var/log", "cd ~", "cd -"] },
  { name: "pwd", cat: "files", desc: "Print the current working directory.", usage: "pwd [-LP]", examples: ["pwd", "pwd -P"] },
  { name: "cp", cat: "files", desc: "Copy files and directories.", usage: "cp [options] source target", examples: ["cp -r dir/ backup/", "cp -a archive/ restore/", "cp file.txt /tmp/"] },
  { name: "mv", cat: "files", desc: "Move or rename files and directories.", usage: "mv [options] source target", examples: ["mv old.txt new.txt", "mv file.txt /tmp/"] },
  { name: "rm", cat: "files", desc: "Remove files or directories.", usage: "rm [options] file...", examples: ["rm -r folder/", "rm -i *.log", "rm -f -- --weird-name"] },
  { name: "mkdir", cat: "files", desc: "Create new directories.", usage: "mkdir [options] directory...", examples: ["mkdir -p a/b/c", "mkdir -m 700 secrets"] },
  { name: "rmdir", cat: "files", desc: "Remove empty directories.", usage: "rmdir [options] directory...", examples: ["rmdir emptydir", "rmdir -p a/b/c"] },
  { name: "touch", cat: "files", desc: "Create an empty file or update its timestamps.", usage: "touch [options] file...", examples: ["touch notes.txt", "touch -d '2026-01-01' file"] },
  { name: "ln", cat: "files", desc: "Create hard or symbolic links between files.", usage: "ln [options] target linkname", examples: ["ln -s /usr/bin/python3 ~/py", "ln file hardlink"] },
  { name: "stat", cat: "files", desc: "Display detailed file or filesystem status.", usage: "stat [options] file", examples: ["stat file", "stat -c '%A %U:%G %s' file"] },
  { name: "file", cat: "files", desc: "Determine the type of a file by its contents.", usage: "file [options] file...", examples: ["file /bin/ls", "file *.txt"] },
  { name: "tree", cat: "files", desc: "List directory contents as an indented tree.", usage: "tree [options] [directory]", examples: ["tree -L 2", "tree -a /etc"] },
  { name: "basename", cat: "files", desc: "Strip the directory part from a path.", usage: "basename name [suffix]", examples: ["basename /var/log/syslog", "basename main.c .c"] },
  { name: "dirname", cat: "files", desc: "Strip the last component from a file path.", usage: "dirname name", examples: ["dirname /etc/ssh/sshd_config"] },
  { name: "realpath", cat: "files", desc: "Print the resolved absolute path of a file.", usage: "realpath [options] file", examples: ["realpath ./link", "realpath -e maybe-missing"] },
  { name: "find", cat: "files", desc: "Search for files in a directory hierarchy.", usage: "find [path...] [expression]", examples: ["find . -name '*.log' -mtime +7", "find /home -type f -size +100M", "find . -name '*.tmp' -delete"] },
  { name: "locate", cat: "files", desc: "Find files by name using a prebuilt index.", usage: "locate [options] pattern", examples: ["locate passwd", "sudo updatedb"] },
  { name: "which", cat: "files", desc: "Show the full path of the command that would run.", usage: "which command", examples: ["which python3"] },
  { name: "whereis", cat: "files", desc: "Locate the binary, source, and man page for a command.", usage: "whereis command", examples: ["whereis gcc"] },
  { name: "type", cat: "files", desc: "Describe how the shell would interpret a command.", usage: "type [-a] name", examples: ["type ls", "type -a python"] },
  { name: "shred", cat: "files", desc: "Overwrite a file repeatedly to hide its contents.", usage: "shred [options] file", examples: ["shred -u secret.txt", "shred -n 5 -z disk.img"] },
  { name: "mktemp", cat: "files", desc: "Create a temporary file or directory safely.", usage: "mktemp [options] [template]", examples: ["mktemp -d", "mktemp /tmp/report.XXXXXX"] },
  { name: "rename", cat: "files", desc: "Rename multiple files using a pattern or expression.", usage: "rename [options] expression file...", examples: ["rename 's/\\.jpeg$/\\.jpg/' *.jpeg", "rename 'y/A-Z/a-z/' *"] },

  /* ---------------- Text Processing ---------------- */
  { name: "cat", cat: "text", desc: "Concatenate files and print them to standard output.", usage: "cat [options] [file...]", examples: ["cat notes.txt", "cat a.txt b.txt > c.txt"] },
  { name: "less", cat: "text", desc: "View file contents one screenful at a time (scroll both ways).", usage: "less [options] file", examples: ["less bigfile.log"] },
  { name: "more", cat: "text", desc: "Page through text output one screen at a time.", usage: "more [options] file", examples: ["dmesg | more"] },
  { name: "head", cat: "text", desc: "Output the first lines of a file.", usage: "head [options] [file]", examples: ["head -n 20 access.log", "head -c 512 binary"] },
  { name: "tail", cat: "text", desc: "Output the last lines of a file; -f follows new output.", usage: "tail [options] [file]", examples: ["tail -f app.log", "tail -n 50 error.log"] },
  { name: "grep", cat: "text", desc: "Search text and files for lines matching a pattern.", usage: "grep [options] pattern [file...]", examples: ["grep -ri \"error\" .", "ps aux | grep nginx", "grep -E 'warn|fail' app.log"] },
  { name: "egrep", cat: "text", desc: "Search using extended regular expressions (grep -E).", usage: "egrep [options] pattern [file...]", examples: ["egrep 'cat|dog' animals.txt"] },
  { name: "sed", cat: "text", desc: "Stream editor for filtering and transforming text.", usage: "sed [options] 'command' [file]", examples: ["sed -i 's/foo/bar/g' file.txt", "sed -n '10,20p' file.txt", "sed '/^#/d' config"] },
  { name: "awk", cat: "text", desc: "Pattern scanning and text processing language.", usage: "awk [options] 'program' [file...]", examples: ["awk '{print $1, $3}' file", "awk -F: '{print $1}' /etc/passwd", "awk '{s+=$1} END {print s}'"] },
  { name: "cut", cat: "text", desc: "Remove sections (fields or characters) from each line.", usage: "cut [options] [file]", examples: ["cut -d: -f1 /etc/passwd", "cut -c1-8 file"] },
  { name: "paste", cat: "text", desc: "Merge lines of files side by side.", usage: "paste [options] [file...]", examples: ["paste -d, a.txt b.txt"] },
  { name: "sort", cat: "text", desc: "Sort lines of text files.", usage: "sort [options] [file]", examples: ["sort -n sizes.txt", "sort -u names.txt", "sort -k2 data.csv"] },
  { name: "uniq", cat: "text", desc: "Report or omit repeated adjacent lines.", usage: "uniq [options] [input]", examples: ["sort names.txt | uniq -c", "uniq -d dupes.txt"] },
  { name: "wc", cat: "text", desc: "Print newline, word, and byte counts.", usage: "wc [options] [file...]", examples: ["wc -l *.c", "wc -w README"] },
  { name: "tr", cat: "text", desc: "Translate, squeeze, or delete characters.", usage: "tr [options] set1 [set2]", examples: ["echo hello | tr 'a-z' 'A-Z'", "tr -d ' ' < file"] },
  { name: "tee", cat: "text", desc: "Read stdin and write it to both stdout and files.", usage: "tee [options] [file...]", examples: ["make 2>&1 | tee build.log", "echo hi | sudo tee /etc/motd"] },
  { name: "fmt", cat: "text", desc: "Simple optimal text formatter (reflows paragraphs).", usage: "fmt [options] [file]", examples: ["fmt -w 60 README"] },
  { name: "fold", cat: "text", desc: "Wrap each input line to fit a specified width.", usage: "fold [options] [file]", examples: ["fold -w 40 long.txt", "fold -s notes.txt"] },
  { name: "nl", cat: "text", desc: "Number the lines of files.", usage: "nl [options] [file]", examples: ["nl code.py"] },
  { name: "rev", cat: "text", desc: "Reverse the characters of each line.", usage: "rev [file]", examples: ["rev file.txt"] },
  { name: "tac", cat: "text", desc: "Concatenate and print files in reverse line order.", usage: "tac [file...]", examples: ["tac app.log | head"] },
  { name: "od", cat: "text", desc: "Dump files in octal, hex, and other formats.", usage: "od [options] [file]", examples: ["od -c file.bin", "od -A x -t x1z file"] },
  { name: "xxd", cat: "text", desc: "Create a hex dump of a file, or reverse it.", usage: "xxd [options] [file]", examples: ["xxd -l 64 binary", "xxd -p file | head"] },
  { name: "strings", cat: "text", desc: "Print printable strings found in binaries.", usage: "strings [options] file", examples: ["strings /bin/bash | grep GLIBC"] },
  { name: "diff", cat: "text", desc: "Compare files line by line.", usage: "diff [options] file1 file2", examples: ["diff -u old.txt new.txt", "diff -r dir1/ dir2/"] },
  { name: "cmp", cat: "text", desc: "Compare two files byte by byte.", usage: "cmp [options] file1 file2", examples: ["cmp a.bin b.bin"] },
  { name: "patch", cat: "text", desc: "Apply a changeset (diff) to an original file.", usage: "patch [options] [file]", examples: ["patch < change.diff", "patch -p1 < fix.patch"] },
  { name: "column", cat: "text", desc: "Format input into aligned columns or tables.", usage: "column [options] [file]", examples: ["mount | column -t", "df -h | column -t"] },
  { name: "expand", cat: "text", desc: "Convert tabs into spaces.", usage: "expand [options] [file]", examples: ["expand Makefile > Makefile.spaces"] },
  { name: "iconv", cat: "text", desc: "Convert text between character encodings.", usage: "iconv -f from -t to [file]", examples: ["iconv -f UTF-8 -t ASCII//TRANSLIT in.txt", "iconv -f ISO-8859-1 -t UTF-8 old.txt > new.txt"] },
  { name: "comm", cat: "text", desc: "Compare two sorted files line by line.", usage: "comm [options] file1 file2", examples: ["comm -12 a.txt b.txt", "comm -23 a.txt b.txt"] },
  { name: "join", cat: "text", desc: "Join lines of two files on a common field.", usage: "join [options] file1 file2", examples: ["join -t, -1 1 -2 1 a.csv b.csv"] },
  { name: "zcat", cat: "text", desc: "View the contents of gzip files without extracting.", usage: "zcat [file.gz...]", examples: ["zcat old.log.gz | grep error"] },
  { name: "zgrep", cat: "text", desc: "Search inside compressed files with grep.", usage: "zgrep [options] pattern file.gz...", examples: ["zgrep 'timeout' *.log.gz"] },

  /* ---------------- System Information ---------------- */
  { name: "uname", cat: "system", desc: "Print kernel and system information.", usage: "uname [options]", examples: ["uname -a", "uname -r"] },
  { name: "hostname", cat: "system", desc: "Show or set the system's host name.", usage: "hostname [options] [name]", examples: ["hostname", "hostname -I"] },
  { name: "hostnamectl", cat: "system", desc: "Query and control the system hostname and settings.", usage: "hostnamectl [command]", examples: ["hostnamectl", "sudo hostnamectl set-hostname web01"] },
  { name: "uptime", cat: "system", desc: "Show how long the system has been running and load averages.", usage: "uptime [options]", examples: ["uptime", "uptime -p"] },
  { name: "whoami", cat: "system", desc: "Print the current effective user name.", usage: "whoami", examples: ["whoami"] },
  { name: "id", cat: "system", desc: "Print real and effective user and group IDs.", usage: "id [options] [user]", examples: ["id", "id -u", "id alice"] },
  { name: "w", cat: "system", desc: "Show who is logged in and what they are doing.", usage: "w [options] [user]", examples: ["w", "w -h"] },
  { name: "who", cat: "system", desc: "Show who is logged on.", usage: "who [options]", examples: ["who", "who -a"] },
  { name: "last", cat: "system", desc: "List recent user logins and reboots.", usage: "last [options] [user...]", examples: ["last -n 10", "last reboot"] },
  { name: "lastlog", cat: "system", desc: "Report the most recent login of all or a given user.", usage: "lastlog [options]", examples: ["lastlog", "lastlog -u root"] },
  { name: "date", cat: "system", desc: "Print or set the system date and time.", usage: "date [options] [+format]", examples: ["date", "date +%Y-%m-%d", "date -u", "date -d 'tomorrow'"] },
  { name: "cal", cat: "system", desc: "Display a calendar.", usage: "cal [options] [[month] year]", examples: ["cal", "cal 2026"] },
  { name: "timedatectl", cat: "system", desc: "Control the system time, date, and timezone.", usage: "timedatectl [command]", examples: ["timedatectl", "sudo timedatectl set-timezone Asia/Jakarta"] },
  { name: "lscpu", cat: "system", desc: "Display CPU architecture information.", usage: "lscpu [options]", examples: ["lscpu"] },
  { name: "lspci", cat: "system", desc: "List all PCI devices (graphics, network, etc.).", usage: "lspci [options]", examples: ["lspci", "lspci -v | grep -A5 VGA"] },
  { name: "lsusb", cat: "system", desc: "List USB devices and controllers.", usage: "lsusb [options]", examples: ["lsusb", "lsusb -t"] },
  { name: "lsmod", cat: "system", desc: "Show the status of loaded kernel modules.", usage: "lsmod", examples: ["lsmod", "lsmod | grep kvm"] },
  { name: "lsmem", cat: "system", desc: "List ranges of available memory blocks.", usage: "lsmem [options]", examples: ["lsmem"] },
  { name: "free", cat: "system", desc: "Display amount of free and used memory.", usage: "free [options]", examples: ["free -h", "free -s 2"] },
  { name: "vmstat", cat: "system", desc: "Report virtual memory, CPU, and IO statistics.", usage: "vmstat [interval [count]]", examples: ["vmstat", "vmstat 1 5"] },
  { name: "iostat", cat: "system", desc: "Report CPU and block device I/O statistics.", usage: "iostat [options] [interval [count]]", examples: ["iostat -x 2"] },
  { name: "mpstat", cat: "system", desc: "Report per-processor CPU statistics.", usage: "mpstat [options] [interval [count]]", examples: ["mpstat -P ALL 1"] },
  { name: "sar", cat: "system", desc: "Collect, report, and save system activity information.", usage: "sar [options] [interval [count]]", examples: ["sar -u 1 5", "sar -r"] },
  { name: "dmesg", cat: "system", desc: "Print or control the kernel ring buffer messages.", usage: "dmesg [options]", examples: ["dmesg -w", "dmesg | grep -i usb", "dmesg -T --level=err"] },
  { name: "journalctl", cat: "system", desc: "Query and display logs from the systemd journal.", usage: "journalctl [options]", examples: ["journalctl -u nginx -f", "journalctl -b -1", "journalctl --since today"] },
  { name: "arch", cat: "system", desc: "Print the machine hardware architecture.", usage: "arch", examples: ["arch"] },
  { name: "nproc", cat: "system", desc: "Print the number of available processing units.", usage: "nproc [options]", examples: ["nproc"] },
  { name: "tty", cat: "system", desc: "Print the file name of the connected terminal.", usage: "tty", examples: ["tty"] },
  { name: "stty", cat: "system", desc: "Change and print terminal line settings.", usage: "stty [options] [setting...]", examples: ["stty -a", "stty size"] },
  { name: "lsb_release", cat: "system", desc: "Print distribution-specific information.", usage: "lsb_release [options]", examples: ["lsb_release -a", "lsb_release -d"] },
  { name: "inxi", cat: "system", desc: "Show a full-featured system information summary.", usage: "inxi [options]", examples: ["inxi -Fxz", "inxi -b"] },

  /* ---------------- Process Management ---------------- */
  { name: "ps", cat: "process", desc: "Report a snapshot of current processes.", usage: "ps [options]", examples: ["ps aux", "ps -ef --forest", "ps -p 1234 -o pid,cmd,%cpu"] },
  { name: "top", cat: "process", desc: "Display running processes and resource usage in real time.", usage: "top [options]", examples: ["top", "top -o %MEM"] },
  { name: "htop", cat: "process", desc: "Interactive, colorful process viewer.", usage: "htop [options]", examples: ["htop", "htop -t"] },
  { name: "kill", cat: "process", desc: "Send a signal (e.g. terminate) to processes by PID.", usage: "kill [options] pid...", examples: ["kill -9 1234", "kill -HUP 4321", "kill -l"] },
  { name: "killall", cat: "process", desc: "Kill processes by exact name.", usage: "killall [options] name...", examples: ["killall firefox", "killall -u bob python"] },
  { name: "pkill", cat: "process", desc: "Signal processes matching a name or pattern.", usage: "pkill [options] pattern", examples: ["pkill -f \"python app.py\"", "pkill -u alice node"] },
  { name: "pgrep", cat: "process", desc: "Find process IDs by name or other attributes.", usage: "pgrep [options] pattern", examples: ["pgrep -a nginx", "pgrep -f node"] },
  { name: "nice", cat: "process", desc: "Run a program with a modified scheduling priority.", usage: "nice [options] command [args]", examples: ["nice -n 10 ./backup.sh", "nice -n -5 make"] },
  { name: "renice", cat: "process", desc: "Change the priority of running processes.", usage: "renice priority [-p pid... | -u user...]", examples: ["sudo renice -n 5 -p 1234"] },
  { name: "nohup", cat: "process", desc: "Run a command immune to hangups, output to a file.", usage: "nohup command [args]", examples: ["nohup ./server.sh &", "nohup long-job.sh > out.log 2>&1 &"] },
  { name: "bg", cat: "process", desc: "Resume a stopped job in the background.", usage: "bg [job_id...]", examples: ["bg", "bg %1"] },
  { name: "fg", cat: "process", desc: "Bring a job to the foreground.", usage: "fg [job_id]", examples: ["fg", "fg %1"] },
  { name: "jobs", cat: "process", desc: "List the shell's active jobs and their states.", usage: "jobs [options]", examples: ["jobs", "jobs -l"] },
  { name: "disown", cat: "process", desc: "Remove a job from the shell's job table so it survives logout.", usage: "disown [job_id...]", examples: ["disown %1", "disown -h %2"] },
  { name: "time", cat: "process", desc: "Measure how long a command takes to run.", usage: "time command [args]", examples: ["time make", "time sleep 1"] },
  { name: "timeout", cat: "process", desc: "Run a command with a time limit, kill it if exceeded.", usage: "timeout [options] duration command", examples: ["timeout 30s ./test.sh", "timeout 5m wget big.iso"] },
  { name: "watch", cat: "process", desc: "Execute a command repeatedly and display the output.", usage: "watch [options] command", examples: ["watch -n 1 'df -h'", "watch -d 'uptime'"] },
  { name: "pstree", cat: "process", desc: "Display running processes as a tree.", usage: "pstree [options]", examples: ["pstree", "pstree -p -u"] },
  { name: "pidof", cat: "process", desc: "Find the process ID of a running program.", usage: "pidof [options] name", examples: ["pidof sshd"] },
  { name: "pidstat", cat: "process", desc: "Report statistics for individual processes.", usage: "pidstat [options] [interval [count]]", examples: ["pidstat -u 2", "pidstat -d 1"] },
  { name: "strace", cat: "process", desc: "Trace system calls and signals of a process.", usage: "strace [options] command | -p pid", examples: ["strace -p 1234", "strace -f -e trace=network curl x.com"] },
  { name: "ltrace", cat: "process", desc: "Trace library calls made by a program.", usage: "ltrace [options] command", examples: ["ltrace ./a.out"] },
  { name: "exec", cat: "process", desc: "Replace the current shell process with a command.", usage: "exec command [args]", examples: ["exec nginx -g \"daemon off;\"", "exec > log.txt 2>&1"] },
  { name: "ulimit", cat: "process", desc: "Get or set resource limits for the shell and its children.", usage: "ulimit [options] [limit]", examples: ["ulimit -a", "ulimit -n 4096"] },
  { name: "trap", cat: "process", desc: "Catch signals or exit events in shell scripts.", usage: "trap 'commands' signal...", examples: ["trap 'rm -f /tmp/tmpfile' EXIT", "trap '' SIGINT"] },
  { name: "lsof", cat: "process", desc: "List open files, sockets, and pipes per process.", usage: "lsof [options] [names]", examples: ["lsof -i :80", "lsof -u alice", "lsof +D /var/www"] }
]);
