/* Linux command database — part 2 of 2 (network, users, packages, archive, disk, shell, services, dev) */
window.CMDS = (window.CMDS || []).concat([

  /* ---------------- Networking ---------------- */
  { name: "ping", cat: "network", desc: "Test reachability of a host and measure latency.", usage: "ping [options] host", examples: ["ping -c 4 google.com", "ping -i 0.2 8.8.8.8"] },
  { name: "ip", cat: "network", desc: "Show and manipulate routing, devices, and addresses (modern).", usage: "ip [options] object command", examples: ["ip a", "ip route", "sudo ip link set eth0 up"] },
  { name: "ifconfig", cat: "network", desc: "Configure network interfaces (legacy).", usage: "ifconfig [interface]", examples: ["ifconfig", "sudo ifconfig eth0 up"] },
  { name: "netstat", cat: "network", desc: "Show network connections, ports, and stats (legacy).", usage: "netstat [options]", examples: ["netstat -tulpn", "netstat -rn"] },
  { name: "ss", cat: "network", desc: "Show socket statistics (modern netstat).", usage: "ss [options]", examples: ["ss -tulpn", "ss -s", "ss -tn state established"] },
  { name: "curl", cat: "network", desc: "Transfer data from or to a server via URLs.", usage: "curl [options] url", examples: ["curl -O https://example.com/file.tgz", "curl -s https://api.example.com", "curl -X POST -d 'a=1' url"] },
  { name: "wget", cat: "network", desc: "Download files from the web non-interactively.", usage: "wget [options] url", examples: ["wget -c big.iso", "wget -r -np -k https://site/"] },
  { name: "ssh", cat: "network", desc: "Securely log into and run commands on a remote machine.", usage: "ssh [options] user@host [command]", examples: ["ssh user@host", "ssh -i key.pem -p 2222 ec2-user@host"] },
  { name: "scp", cat: "network", desc: "Copy files between hosts over SSH.", usage: "scp [options] source target", examples: ["scp file.txt user@host:/tmp/", "scp -r dir/ user@host:~/backup/"] },
  { name: "sftp", cat: "network", desc: "Interactive secure file transfer session.", usage: "sftp [options] user@host", examples: ["sftp user@host", "sftp -P 2222 user@host"] },
  { name: "rsync", cat: "network", desc: "Fast, incremental file transfer and synchronization.", usage: "rsync [options] source target", examples: ["rsync -avz dir/ user@host:/backup/", "rsync -av --delete src/ dst/"] },
  { name: "nc", cat: "network", desc: "Netcat: read and write TCP/UDP connections.", usage: "nc [options] host port", examples: ["nc -zv host 80", "nc -l 9999", "nc host 9999 < file"] },
  { name: "nmap", cat: "network", desc: "Network exploration and security port scanning.", usage: "nmap [options] target", examples: ["nmap -p 1-1000 host", "nmap -sV 192.168.1.0/24"] },
  { name: "traceroute", cat: "network", desc: "Print the route packets take to a host.", usage: "traceroute [options] host", examples: ["traceroute 8.8.8.8"] },
  { name: "mtr", cat: "network", desc: "Combine traceroute and ping into a live network diagnostic.", usage: "mtr [options] host", examples: ["mtr -r host", "mtr -c 100 host"] },
  { name: "dig", cat: "network", desc: "Query DNS name servers for records.", usage: "dig [options] name [type] [@server]", examples: ["dig example.com A", "dig +short example.com", "dig MX example.com"] },
  { name: "nslookup", cat: "network", desc: "Query Internet name servers interactively.", usage: "nslookup [name] [server]", examples: ["nslookup example.com", "nslookup example.com 8.8.8.8"] },
  { name: "host", cat: "network", desc: "Simple DNS lookup utility.", usage: "host [options] name [server]", examples: ["host example.com"] },
  { name: "whois", cat: "network", desc: "Look up domain registration and ownership info.", usage: "whois [options] name", examples: ["whois example.com"] },
  { name: "route", cat: "network", desc: "Show or change the IP routing table (legacy).", usage: "route [options]", examples: ["route -n"] },
  { name: "arp", cat: "network", desc: "Show or modify the IP-to-MAC address cache.", usage: "arp [options]", examples: ["arp -a"] },
  { name: "ethtool", cat: "network", desc: "Query and control network driver and hardware settings.", usage: "ethtool [options] interface", examples: ["ethtool eth0", "sudo ethtool -s eth0 speed 1000 duplex full"] },
  { name: "tcpdump", cat: "network", desc: "Capture and analyze network packets.", usage: "tcpdump [options] [filter]", examples: ["sudo tcpdump -i eth0 port 80", "sudo tcpdump -w cap.pcap host 10.0.0.5"] },
  { name: "iptables", cat: "network", desc: "Configure the legacy Linux kernel firewall.", usage: "iptables [options] rule", examples: ["sudo iptables -L -n", "sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT"] },
  { name: "nft", cat: "network", desc: "Configure the modern netfilter firewall (nftables).", usage: "nft [options] command", examples: ["sudo nft list ruleset", "sudo nft add table inet filter"] },
  { name: "ufw", cat: "network", desc: "Uncomplicated Firewall: simple frontend for iptables.", usage: "ufw command [args]", examples: ["sudo ufw allow 22", "sudo ufw enable", "sudo ufw status"] },
  { name: "firewall-cmd", cat: "network", desc: "Control the firewalld firewall daemon.", usage: "firewall-cmd [options]", examples: ["sudo firewall-cmd --list-all", "sudo firewall-cmd --add-service=http --permanent"] },
  { name: "ssh-keygen", cat: "network", desc: "Generate and manage SSH key pairs.", usage: "ssh-keygen [options]", examples: ["ssh-keygen -t ed25519 -C \"me@host\"", "ssh-keygen -f ~/.ssh/id_rsa"] },
  { name: "ssh-copy-id", cat: "network", desc: "Install your public key on a remote server for login.", usage: "ssh-copy-id [options] user@host", examples: ["ssh-copy-id user@host"] },
  { name: "socat", cat: "network", desc: "Multipurpose relay for bidirectional data streams.", usage: "socat [options] addr1 addr2", examples: ["socat TCP-LISTEN:8080,fork TCP:host:80", "socat UNIX-CONNECT:/tmp/sock -"] },
  { name: "telnet", cat: "network", desc: "Connect to remote services over TCP (unencrypted, legacy).", usage: "telnet host [port]", examples: ["telnet localhost 25"] },

  /* ---------------- Users & Permissions ---------------- */
  { name: "useradd", cat: "users", desc: "Create a new user account (low-level).", usage: "useradd [options] username", examples: ["sudo useradd -m -s /bin/bash alice", "sudo useradd -G docker,sudo bob"] },
  { name: "userdel", cat: "users", desc: "Delete a user account and optionally their files.", usage: "userdel [options] username", examples: ["sudo userdel -r alice"] },
  { name: "usermod", cat: "users", desc: "Modify an existing user account.", usage: "usermod [options] username", examples: ["sudo usermod -aG docker alice", "sudo usermod -s /bin/zsh bob"] },
  { name: "adduser", cat: "users", desc: "Friendly interactive user creation (Debian/Ubuntu).", usage: "adduser [options] username", examples: ["sudo adduser alice"] },
  { name: "deluser", cat: "users", desc: "Remove a user or group (Debian/Ubuntu).", usage: "deluser [options] username", examples: ["sudo deluser --remove-home alice"] },
  { name: "groupadd", cat: "users", desc: "Create a new group.", usage: "groupadd [options] group", examples: ["sudo groupadd devs"] },
  { name: "groupdel", cat: "users", desc: "Delete a group.", usage: "groupdel group", examples: ["sudo groupdel devs"] },
  { name: "groupmod", cat: "users", desc: "Modify a group definition.", usage: "groupmod [options] group", examples: ["sudo groupmod -n newname oldname"] },
  { name: "groups", cat: "users", desc: "Print the groups a user belongs to.", usage: "groups [username]", examples: ["groups", "groups alice"] },
  { name: "newgrp", cat: "users", desc: "Log in to a new group in the current session.", usage: "newgrp [group]", examples: ["newgrp docker"] },
  { name: "gpasswd", cat: "users", desc: "Administer /etc/group (manage group members).", usage: "gpasswd [options] group", examples: ["sudo gpasswd -a alice devs", "sudo gpasswd -d bob devs"] },
  { name: "passwd", cat: "users", desc: "Change a user's password.", usage: "passwd [options] [username]", examples: ["passwd", "sudo passwd alice", "sudo passwd -l alice"] },
  { name: "chage", cat: "users", desc: "Change user password expiry information.", usage: "chage [options] username", examples: ["sudo chage -l alice", "sudo chage -M 90 alice"] },
  { name: "chown", cat: "users", desc: "Change file owner and group.", usage: "chown [options] owner[:group] file...", examples: ["sudo chown -R www-data:www-data /var/www", "chown alice notes.txt"] },
  { name: "chgrp", cat: "users", desc: "Change group ownership of files.", usage: "chgrp [options] group file...", examples: ["sudo chgrp -R devs /srv/project"] },
  { name: "chmod", cat: "users", desc: "Change file mode bits (permissions).", usage: "chmod [options] mode file...", examples: ["chmod 755 script.sh", "chmod u+x run.sh", "chmod -R g+w team/"] },
  { name: "umask", cat: "users", desc: "Get or set the default file creation permission mask.", usage: "umask [mask]", examples: ["umask", "umask 027"] },
  { name: "getent", cat: "users", desc: "Get entries from system databases (passwd, group, hosts...).", usage: "getent database [key]", examples: ["getent passwd alice", "getent hosts example.com"] },
  { name: "su", cat: "users", desc: "Run a shell as another user or root.", usage: "su [options] [user]", examples: ["su -", "su - alice"] },
  { name: "sudo", cat: "users", desc: "Execute a command as another user, usually root.", usage: "sudo [options] command", examples: ["sudo apt update", "sudo -i", "sudo -u postgres psql"] },
  { name: "visudo", cat: "users", desc: "Safely edit the sudoers file with validation.", usage: "visudo [options]", examples: ["sudo visudo", "sudo visudo -f /etc/sudoers.d/team"] },
  { name: "login", cat: "users", desc: "Begin a session on the system.", usage: "login [username]", examples: ["login", "login alice"] },
  { name: "logout", cat: "users", desc: "Exit a login shell.", usage: "logout", examples: ["logout"] },

  /* ---------------- Package Management ---------------- */
  { name: "apt", cat: "packages", desc: "High-level package manager for Debian/Ubuntu.", usage: "apt command [args]", examples: ["sudo apt update && sudo apt upgrade", "sudo apt install htop", "apt search nginx"] },
  { name: "apt-get", cat: "packages", desc: "Command-line interface to the Debian package system.", usage: "apt-get command [args]", examples: ["sudo apt-get install -y build-essential", "sudo apt-get autoremove"] },
  { name: "aptitude", cat: "packages", desc: "Advanced text-based frontend for apt.", usage: "aptitude command [args]", examples: ["aptitude search nginx", "sudo aptitude install vim"] },
  { name: "dpkg", cat: "packages", desc: "Low-level Debian package manager for .deb files.", usage: "dpkg [options] action", examples: ["sudo dpkg -i pkg.deb", "dpkg -l | grep nginx", "dpkg -L coreutils"] },
  { name: "yum", cat: "packages", desc: "Package manager for RHEL/CentOS 7 and older.", usage: "yum command [args]", examples: ["sudo yum install nginx", "sudo yum update"] },
  { name: "dnf", cat: "packages", desc: "Next-generation package manager for Fedora/RHEL 8+.", usage: "dnf command [args]", examples: ["sudo dnf upgrade", "sudo dnf install git"] },
  { name: "rpm", cat: "packages", desc: "RPM package manager for .rpm packages.", usage: "rpm [options] package", examples: ["rpm -qa | grep bash", "sudo rpm -ivh pkg.rpm", "rpm -ql nginx"] },
  { name: "pacman", cat: "packages", desc: "Package manager for Arch Linux.", usage: "pacman [options] [targets]", examples: ["sudo pacman -Syu", "sudo pacman -S htop", "pacman -Ss vim"] },
  { name: "yay", cat: "packages", desc: "AUR helper and pacman wrapper for Arch Linux.", usage: "yay [options] [targets]", examples: ["yay -S visual-studio-code-bin", "yay -Syu"] },
  { name: "zypper", cat: "packages", desc: "Package manager for openSUSE/SUSE.", usage: "zypper command [args]", examples: ["sudo zypper install vim", "sudo zypper refresh"] },
  { name: "apk", cat: "packages", desc: "Package manager for Alpine Linux.", usage: "apk command [args]", examples: ["sudo apk add curl", "sudo apk update"] },
  { name: "snap", cat: "packages", desc: "Install and manage snap packages (Ubuntu).", usage: "snap command [args]", examples: ["sudo snap install code --classic", "snap list"] },
  { name: "flatpak", cat: "packages", desc: "Install and manage sandboxed Flatpak applications.", usage: "flatpak command [args]", examples: ["flatpak install flathub org.gimp.GIMP", "flatpak list"] },
  { name: "pip", cat: "packages", desc: "Python package installer.", usage: "pip command [args]", examples: ["pip install requests", "pip list", "pip install -r requirements.txt"] },
  { name: "npm", cat: "packages", desc: "Node.js package manager.", usage: "npm command [args]", examples: ["npm install express", "npm run build", "npm i -g typescript"] },
  { name: "gem", cat: "packages", desc: "RubyGems package manager for Ruby.", usage: "gem command [args]", examples: ["gem install bundler", "gem list"] },
  { name: "cargo", cat: "packages", desc: "Rust package manager and build tool.", usage: "cargo command [args]", examples: ["cargo build --release", "cargo add serde"] },

  /* ---------------- Archives & Compression ---------------- */
  { name: "tar", cat: "archive", desc: "Archive files; the standard tarball tool.", usage: "tar [options] [files...]", examples: ["tar -czvf archive.tar.gz dir/", "tar -xzvf archive.tar.gz", "tar -tf archive.tar.gz"] },
  { name: "gzip", cat: "archive", desc: "Compress files using DEFLATE.", usage: "gzip [options] file", examples: ["gzip -9 big.log", "gzip -k data.txt"] },
  { name: "gunzip", cat: "archive", desc: "Decompress gzip-compressed files.", usage: "gunzip [options] file.gz", examples: ["gunzip file.gz", "gunzip -k file.gz"] },
  { name: "bzip2", cat: "archive", desc: "Compress files with block-sorting (better ratio than gzip).", usage: "bzip2 [options] file", examples: ["bzip2 -9 data.txt", "bzip2 -dk data.txt"] },
  { name: "xz", cat: "archive", desc: "Compress files with LZMA2 (high ratio).", usage: "xz [options] file", examples: ["xz -k huge.sql", "xz -9 -T0 kernel.tar"] },
  { name: "zip", cat: "archive", desc: "Create ZIP archives (Windows-compatible).", usage: "zip [options] archive files...", examples: ["zip -r site.zip public/", "zip -e secret.zip file"] },
  { name: "unzip", cat: "archive", desc: "Extract, list, or test ZIP archives.", usage: "unzip [options] archive.zip", examples: ["unzip archive.zip -d out/", "unzip -l archive.zip"] },
  { name: "7z", cat: "archive", desc: "7-Zip archiver with high compression.", usage: "7z command archive [files]", examples: ["7z a out.7z dir/", "7z x archive.7z"] },
  { name: "zstd", cat: "archive", desc: "Zstandard: fast modern compression.", usage: "zstd [options] file", examples: ["zstd -19 big.tar", "zstd -d file.tar.zst"] },
  { name: "lz4", cat: "archive", desc: "Extremely fast compression.", usage: "lz4 [options] file", examples: ["lz4 -9 data.bin", "lz4 -d data.bin.lz4"] },
  { name: "cpio", cat: "archive", desc: "Copy files to and from archives (used by initramfs).", usage: "cpio [options]", examples: ["ls | cpio -ov > backup.cpio", "cpio -idmv < backup.cpio"] },
  { name: "ar", cat: "archive", desc: "Create, modify, and extract static library archives.", usage: "ar [options] archive files", examples: ["ar rcs libfoo.a foo.o", "ar x libfoo.a"] },
  { name: "compress", cat: "archive", desc: "Legacy LZW file compression (.Z files).", usage: "compress [options] file", examples: ["compress old.txt"] },

  /* ---------------- Disks & Storage ---------------- */
  { name: "df", cat: "disk", desc: "Report filesystem disk space usage.", usage: "df [options] [file...]", examples: ["df -h", "df -h /var"] },
  { name: "du", cat: "disk", desc: "Estimate file and directory space usage.", usage: "du [options] [path...]", examples: ["du -sh /var/log", "du -h --max-depth=1 / | sort -h"] },
  { name: "lsblk", cat: "disk", desc: "List information about block devices.", usage: "lsblk [options]", examples: ["lsblk", "lsblk -f"] },
  { name: "mount", cat: "disk", desc: "Mount a filesystem.", usage: "mount [options] device directory", examples: ["sudo mount /dev/sdb1 /mnt/usb", "mount | column -t"] },
  { name: "umount", cat: "disk", desc: "Unmount a filesystem.", usage: "umount [options] directory|device", examples: ["sudo umount /mnt/usb"] },
  { name: "findmnt", cat: "disk", desc: "Find and display mounted filesystems.", usage: "findmnt [options] [target]", examples: ["findmnt", "findmnt /home"] },
  { name: "fdisk", cat: "disk", desc: "Manipulate disk partition tables.", usage: "fdisk [options] device", examples: ["sudo fdisk -l", "sudo fdisk /dev/sdb"] },
  { name: "parted", cat: "disk", desc: "Partition manipulation program (GPT support).", usage: "parted [options] [device [command]]", examples: ["sudo parted /dev/sdb print", "sudo parted -a opt /dev/sdb mkpart primary 0% 100%"] },
  { name: "blkid", cat: "disk", desc: "Locate and print block device attributes (UUID, type).", usage: "blkid [options] [device...]", examples: ["blkid", "sudo blkid /dev/sda1"] },
  { name: "mkfs", cat: "disk", desc: "Build a Linux filesystem on a partition.", usage: "mkfs [-t type] device", examples: ["sudo mkfs.ext4 /dev/sdb1", "sudo mkfs.vfat /dev/sdc1"] },
  { name: "fsck", cat: "disk", desc: "Check and repair a Linux filesystem.", usage: "fsck [options] device", examples: ["sudo fsck -y /dev/sdb1"] },
  { name: "dd", cat: "disk", desc: "Convert and copy raw data (disk images, boot media).", usage: "dd if=input of=output [bs=N count=N]", examples: ["sudo dd if=ubuntu.iso of=/dev/sdb bs=4M status=progress", "dd if=/dev/zero of=test.img bs=1M count=100"] },
  { name: "sync", cat: "disk", desc: "Flush pending filesystem writes to disk.", usage: "sync", examples: ["sync"] },
  { name: "eject", cat: "disk", desc: "Eject removable media.", usage: "eject [options] [device]", examples: ["eject /dev/sr0"] },
  { name: "hdparm", cat: "disk", desc: "Get and set SATA/IDE hard disk parameters.", usage: "hdparm [options] device", examples: ["sudo hdparm -I /dev/sda", "sudo hdparm -t /dev/sda"] },
  { name: "smartctl", cat: "disk", desc: "Query disk S.M.A.R.T. health and diagnostics.", usage: "smartctl [options] device", examples: ["sudo smartctl -a /dev/sda", "sudo smartctl -t short /dev/sda"] },
  { name: "swapon", cat: "disk", desc: "Enable swap devices and files.", usage: "swapon [options] [device...]", examples: ["sudo swapon -a", "sudo swapon /swapfile"] },
  { name: "swapoff", cat: "disk", desc: "Disable swap devices and files.", usage: "swapoff [options] [device...]", examples: ["sudo swapoff /swapfile"] },
  { name: "mkswap", cat: "disk", desc: "Set up a Linux swap area.", usage: "mkswap [options] device", examples: ["sudo mkswap /swapfile"] },
  { name: "losetup", cat: "disk", desc: "Set up and control loop devices.", usage: "losetup [options] loopdev file", examples: ["sudo losetup -f --show disk.img"] },
  { name: "tune2fs", cat: "disk", desc: "Adjust tunable ext2/3/4 filesystem parameters.", usage: "tune2fs [options] device", examples: ["sudo tune2fs -l /dev/sda1"] },
  { name: "resize2fs", cat: "disk", desc: "Resize ext2/3/4 filesystems.", usage: "resize2fs [options] device [size]", examples: ["sudo resize2fs /dev/sda1"] },
  { name: "badblocks", cat: "disk", desc: "Search a device for bad blocks.", usage: "badblocks [options] device", examples: ["sudo badblocks -sv /dev/sdb"] },

  /* ---------------- Shell & Utilities ---------------- */
  { name: "bash", cat: "shell", desc: "The GNU Bourne-Again SHell — the default Linux shell.", usage: "bash [options] [file]", examples: ["bash", "bash script.sh", "bash -x script.sh"] },
  { name: "sh", cat: "shell", desc: "The POSIX Bourne shell (or a compatible shell).", usage: "sh [options] [file]", examples: ["sh setup.sh"] },
  { name: "zsh", cat: "shell", desc: "The Z shell with extended features.", usage: "zsh [options] [file]", examples: ["zsh"] },
  { name: "fish", cat: "shell", desc: "Friendly interactive shell with smart defaults.", usage: "fish [options]", examples: ["fish"] },
  { name: "source", cat: "shell", desc: "Execute commands from a file in the current shell.", usage: "source file [args]", examples: ["source ~/.bashrc", "source venv/bin/activate"] },
  { name: "export", cat: "shell", desc: "Set environment variables for future child processes.", usage: "export name[=value]", examples: ["export PATH=$PATH:/opt/bin", "export EDITOR=vim"] },
  { name: "unset", cat: "shell", desc: "Remove a variable or function from the environment.", usage: "unset name", examples: ["unset MYVAR"] },
  { name: "alias", cat: "shell", desc: "Create a shortcut name for a command.", usage: "alias [name='command']", examples: ["alias ll='ls -la'", "alias"] },
  { name: "unalias", cat: "shell", desc: "Remove an alias definition.", usage: "unalias name", examples: ["unalias ll"] },
  { name: "env", cat: "shell", desc: "Run a program with a modified environment, or print it.", usage: "env [options] [name=value] [command]", examples: ["env | grep HOME", "env -i bash", "env FOO=bar ./app"] },
  { name: "printenv", cat: "shell", desc: "Print environment variables.", usage: "printenv [name...]", examples: ["printenv PATH", "printenv"] },
  { name: "set", cat: "shell", desc: "Show or change shell options and positional parameters.", usage: "set [options]", examples: ["set -euo pipefail", "set -x"] },
  { name: "history", cat: "shell", desc: "Display or manage the command history list.", usage: "history [n]", examples: ["history 20", "history | grep git"] },
  { name: "man", cat: "shell", desc: "Read the reference manual pages for commands.", usage: "man [section] command", examples: ["man grep", "man 5 passwd", "man -k compress"] },
  { name: "info", cat: "shell", desc: "Read Info-format documentation.", usage: "info [node]", examples: ["info coreutils"] },
  { name: "whatis", cat: "shell", desc: "Display one-line manual page descriptions.", usage: "whatis command", examples: ["whatis ls"] },
  { name: "apropos", cat: "shell", desc: "Search man page names and descriptions by keyword.", usage: "apropos keyword", examples: ["apropos compress"] },
  { name: "help", cat: "shell", desc: "Show help for bash built-in commands.", usage: "help [command]", examples: ["help cd", "help"] },
  { name: "xargs", cat: "shell", desc: "Build and execute command lines from standard input.", usage: "xargs [options] [command]", examples: ["find . -name '*.tmp' | xargs rm -f", "xargs -n1 -P4 -I{} ./work {}"] },
  { name: "echo", cat: "shell", desc: "Print text or variable values to stdout.", usage: "echo [options] [text]", examples: ["echo \"Hello $USER\"", "echo -e 'a\\tb'"] },
  { name: "printf", cat: "shell", desc: "Print formatted text (C-style formatting).", usage: "printf format [args]", examples: ["printf '%-10s %d\\n' name 42"] },
  { name: "test", cat: "shell", desc: "Evaluate conditional expressions (also written as [ ]).", usage: "test expression", examples: ["test -f file && echo exists", "[ -d /tmp ] && echo dir"] },
  { name: "expr", cat: "shell", desc: "Evaluate arithmetic and string expressions.", usage: "expr expression", examples: ["expr 5 + 3", "expr length \"hello\""] },
  { name: "seq", cat: "shell", desc: "Print a sequence of numbers.", usage: "seq [first [incr]] last", examples: ["seq 1 10", "seq 0 2 10"] },
  { name: "yes", cat: "shell", desc: "Repeatedly output a string until killed (auto-confirm).", usage: "yes [string]", examples: ["yes | ./installer.sh", "yes n | ./risky.sh"] },
  { name: "sleep", cat: "shell", desc: "Pause execution for a specified duration.", usage: "sleep number[suffix]", examples: ["sleep 5", "sleep 1m30s"] },
  { name: "exit", cat: "shell", desc: "Exit the shell with a status code.", usage: "exit [status]", examples: ["exit", "exit 0"] },
  { name: "clear", cat: "shell", desc: "Clear the terminal screen.", usage: "clear", examples: ["clear"] },
  { name: "screen", cat: "shell", desc: "Terminal multiplexer: detachable sessions (classic).", usage: "screen [options] [command]", examples: ["screen -S work", "screen -r work", "screen -ls"] },
  { name: "tmux", cat: "shell", desc: "Modern terminal multiplexer with panes and sessions.", usage: "tmux [command] [args]", examples: ["tmux new -s dev", "tmux attach -t dev", "tmux ls"] },
  { name: "at", cat: "shell", desc: "Queue a one-time job for later execution.", usage: "at [options] time", examples: ["echo './backup.sh' | at now + 5 minutes", "atq"] },
  { name: "crontab", cat: "shell", desc: "Manage tables of scheduled recurring cron jobs.", usage: "crontab [options] [file]", examples: ["crontab -e", "crontab -l"] },
  { name: "chroot", cat: "shell", desc: "Run a command with a different root directory.", usage: "chroot newroot [command]", examples: ["sudo chroot /mnt/recovery /bin/bash"] },
  { name: "script", cat: "shell", desc: "Record everything typed in a terminal session.", usage: "script [options] [file]", examples: ["script session.log", "script -c 'make test' out.txt"] },
  { name: "read", cat: "shell", desc: "Read a line from stdin into shell variables.", usage: "read [options] [name...]", examples: ["read -p 'Name: ' name", "read -s -p 'Password: ' pw"] },
  { name: "getopts", cat: "shell", desc: "Parse positional parameters/options in shell scripts.", usage: "getopts optstring name", examples: ["while getopts \"ab:\" opt; do echo $opt; done"] },
  { name: "logger", cat: "shell", desc: "Write messages to the system log (syslog/journal).", usage: "logger [options] message", examples: ["logger \"Backup finished\""] },
  { name: "wall", cat: "shell", desc: "Broadcast a message to all logged-in users.", usage: "wall [message]", examples: ["sudo wall 'Server reboots in 5 min'"] },
  { name: "write", cat: "shell", desc: "Send a message to another logged-in user's terminal.", usage: "write user [tty]", examples: ["write alice"] },
  { name: "mesg", cat: "shell", desc: "Allow or deny write/talk messages to your terminal.", usage: "mesg [y|n]", examples: ["mesg n"] },

  /* ---------------- Services & System Control ---------------- */
  { name: "systemctl", cat: "services", desc: "Control systemd units: services, sockets, targets.", usage: "systemctl command unit", examples: ["systemctl status nginx", "sudo systemctl enable --now docker", "sudo systemctl restart sshd"] },
  { name: "service", cat: "services", desc: "Manage SysV init scripts (legacy service control).", usage: "service name command", examples: ["sudo service apache2 restart", "sudo service cron status"] },
  { name: "shutdown", cat: "services", desc: "Halt, power off, or reboot the system safely.", usage: "shutdown [options] [time] [message]", examples: ["sudo shutdown -h now", "sudo shutdown -r +10 'rebooting'"] },
  { name: "reboot", cat: "services", desc: "Reboot the machine.", usage: "reboot [options]", examples: ["sudo reboot"] },
  { name: "poweroff", cat: "services", desc: "Shut down and power off the machine.", usage: "poweroff [options]", examples: ["sudo poweroff"] },
  { name: "halt", cat: "services", desc: "Stop the system (do not necessarily power off).", usage: "halt [options]", examples: ["sudo halt"] },
  { name: "init", cat: "services", desc: "Change the system runlevel (legacy SysV).", usage: "init [runlevel]", examples: ["sudo init 3"] },
  { name: "chkconfig", cat: "services", desc: "Manage service runlevel links on RHEL-family systems.", usage: "chkconfig [options] [service]", examples: ["sudo chkconfig nginx on", "chkconfig --list"] },
  { name: "systemd-run", cat: "services", desc: "Run a program as a transient systemd service or timer.", usage: "systemd-run [options] command", examples: ["sudo systemd-run --unit=cleanup rm -rf /tmp/x", "sudo systemd-run --on-calendar=hourly ./job.sh"] },
  { name: "loginctl", cat: "services", desc: "Control the systemd login manager (sessions, seats, users).", usage: "loginctl command [args]", examples: ["loginctl list-sessions", "loginctl terminate-user alice"] },
  { name: "sysctl", cat: "services", desc: "Configure kernel parameters at runtime.", usage: "sysctl [options] [name[=value]]", examples: ["sysctl -a | grep tcp", "sudo sysctl -w vm.swappiness=10"] },
  { name: "modprobe", cat: "services", desc: "Add or remove kernel modules with dependency handling.", usage: "modprobe [options] module", examples: ["sudo modprobe kvm", "sudo modprobe -r kvm"] },
  { name: "insmod", cat: "services", desc: "Insert a kernel module directly.", usage: "insmod module.ko [params]", examples: ["sudo insmod ./driver.ko"] },
  { name: "rmmod", cat: "services", desc: "Remove a loaded kernel module.", usage: "rmmod module", examples: ["sudo rmmod kvm"] },
  { name: "systemd-analyze", cat: "services", desc: "Analyze system boot-up performance.", usage: "systemd-analyze [command]", examples: ["systemd-analyze blame", "systemd-analyze critical-chain"] },

  /* ---------------- Developer Tools ---------------- */
  { name: "git", cat: "dev", desc: "Distributed version control system.", usage: "git command [args]", examples: ["git clone https://github.com/user/repo", "git status", "git log --oneline --graph"] },
  { name: "gcc", cat: "dev", desc: "The GNU C compiler.", usage: "gcc [options] file.c", examples: ["gcc -O2 main.c -o main", "gcc -Wall -g app.c"] },
  { name: "g++", cat: "dev", desc: "The GNU C++ compiler.", usage: "g++ [options] file.cpp", examples: ["g++ -std=c++17 app.cpp -o app"] },
  { name: "make", cat: "dev", desc: "Build programs from Makefile rules.", usage: "make [options] [target]", examples: ["make", "make -j8", "sudo make install"] },
  { name: "gdb", cat: "dev", desc: "The GNU debugger.", usage: "gdb [options] [program]", examples: ["gdb ./a.out", "sudo gdb -p 1234"] },
  { name: "ldd", cat: "dev", desc: "Print shared library dependencies of a binary.", usage: "ldd binary", examples: ["ldd /bin/ls"] },
  { name: "strip", cat: "dev", desc: "Discard symbols from object files and binaries.", usage: "strip [options] file", examples: ["strip app"] },
  { name: "objdump", cat: "dev", desc: "Display information from object files and binaries.", usage: "objdump [options] file", examples: ["objdump -d app | less", "objdump -T libfoo.so"] },
  { name: "nm", cat: "dev", desc: "List symbols from object files.", usage: "nm [options] file", examples: ["nm -D /usr/lib/x86_64-linux-gnu/libc.so.6"] },
  { name: "readelf", cat: "dev", desc: "Display information about ELF binaries.", usage: "readelf [options] file", examples: ["readelf -h /bin/ls"] },
  { name: "bc", cat: "dev", desc: "Arbitrary-precision command-line calculator.", usage: "bc [options]", examples: ["echo 'scale=2; 22/7' | bc", "echo 'sqrt(2)' | bc -l"] },
  { name: "md5sum", cat: "dev", desc: "Compute and check MD5 message digests.", usage: "md5sum file...", examples: ["md5sum file.iso", "md5sum -c sums.txt"] },
  { name: "sha256sum", cat: "dev", desc: "Compute and check SHA-256 hashes.", usage: "sha256sum file...", examples: ["sha256sum release.tar.gz", "sha256sum -c SHA256SUMS"] },
  { name: "sha1sum", cat: "dev", desc: "Compute and check SHA-1 hashes.", usage: "sha1sum file...", examples: ["sha1sum file.bin"] },
  { name: "cksum", cat: "dev", desc: "Print CRC checksum and byte count of files.", usage: "cksum file...", examples: ["cksum data.bin"] },
  { name: "base64", cat: "dev", desc: "Base64 encode or decode data.", usage: "base64 [options] [file]", examples: ["echo -n secret | base64", "base64 -d encoded.txt"] },
  { name: "mkfifo", cat: "dev", desc: "Create FIFOs (named pipes) for inter-process streams.", usage: "mkfifo [options] name", examples: ["mkfifo /tmp/pipe"] },
  { name: "dos2unix", cat: "dev", desc: "Convert text file line endings from Windows to Unix.", usage: "dos2unix [options] file", examples: ["dos2unix script.sh"] },
  { name: "xdg-open", cat: "dev", desc: "Open a file or URL with the default desktop application.", usage: "xdg-open file|url", examples: ["xdg-open report.pdf", "xdg-open https://example.com"] },
  { name: "expect", cat: "dev", desc: "Automate interactive programs (scripted dialogues).", usage: "expect [options] [file]", examples: ["expect deploy.exp"] },
  { name: "units", cat: "dev", desc: "Convert quantities between units of measure.", usage: "units [options]", examples: ["units '10 miles' km"] },
  { name: "factor", cat: "dev", desc: "Print the prime factors of numbers.", usage: "factor number...", examples: ["factor 123456"] },
  { name: "shuf", cat: "dev", desc: "Generate random permutations of lines.", usage: "shuf [options] [file]", examples: ["shuf -n 5 names.txt", "shuf -i 1-100 -n 1"] },
  { name: "openssl", cat: "dev", desc: "Cryptography toolkit: TLS, certificates, keys, and digests.", usage: "openssl command [options]", examples: ["openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem", "openssl s_client -connect example.com:443", "openssl rand -base64 32"] },
  { name: "gpg", cat: "dev", desc: "GNU Privacy Guard: encrypt, sign, and verify files and messages.", usage: "gpg [options] [files]", examples: ["gpg -c secret.txt", "gpg --decrypt secret.txt.gpg", "gpg --verify file.sig file"] },
  { name: "unix2dos", cat: "dev", desc: "Convert text file line endings from Unix to DOS.", usage: "unix2dos [options] file", examples: ["unix2dos notes.txt", "unix2dos -n in.txt out.txt"] },
  { name: "xdg-mime", cat: "dev", desc: "Query MIME types and default applications on the desktop.", usage: "xdg-mime command [args]", examples: ["xdg-mime query filetype photo.jpg", "xdg-mime query default image/png"] }
]);
