/* Exit status + environment data — part 1 of 3 (files, text, system) */
var OK = [["0", "Success"], ["1", "An error occurred"]];

window.EXITSTATUS = Object.assign(window.EXITSTATUS || {}, {
  /* files */
  ls: OK,
  cd: [["0", "Success"], ["1", "Directory does not exist or is not accessible"]],
  pwd: OK, cp: OK, mv: OK, rm: OK, mkdir: OK, rmdir: OK, touch: OK, ln: OK, stat: OK, file: OK, tree: OK,
  basename: OK, dirname: OK, realpath: OK,
  find: [["0", "All files were processed successfully"], ["1", "Errors occurred while processing some files"]],
  locate: OK,
  which: [["0", "All named commands were found"], ["1", "One or more commands were not found"], ["2", "Invalid usage"]],
  whereis: OK,
  type: [["0", "All names were found"], ["1", "One or more names were not found"]],
  shred: OK, mktemp: OK,
  rename: [["0", "All requested renames succeeded"], ["1", "All requested renames failed"], ["2", "Some renames failed"]],

  /* text */
  cat: OK, less: OK, more: OK, head: OK, tail: OK,
  grep: [["0", "At least one line was selected (a match was found)"], ["1", "No lines were selected"], ["2", "An error occurred"]],
  egrep: [["0", "At least one line was selected (a match was found)"], ["1", "No lines were selected"], ["2", "An error occurred"]],
  sed: [["0", "Success"], ["1", "Invalid command, syntax, or script file"], ["2", "One or more input files could not be opened"], ["4", "I/O error or serious runtime error"]],
  awk: [["0", "Success"], ["Non-zero", "An error occurred, or the value passed to exit in the program"]],
  cut: OK, paste: OK, sort: OK, uniq: OK, wc: OK, tr: OK, tee: OK, fmt: OK, fold: OK, nl: OK, rev: OK, tac: OK,
  od: OK, xxd: OK, strings: OK,
  diff: [["0", "The files are identical"], ["1", "The files differ"], ["2", "Trouble (e.g. a file could not be read)"]],
  cmp: [["0", "The files are identical"], ["1", "The files differ"], ["2", "Trouble (e.g. a file could not be read)"]],
  patch: [["0", "All hunks applied successfully"], ["1", "Some hunks failed or contained warnings"], ["2", "Serious trouble"]],
  column: OK, expand: OK, iconv: OK, comm: OK, join: OK, zcat: OK,
  zgrep: [["0", "At least one line was selected (a match was found)"], ["1", "No lines were selected"], ["2", "An error occurred"]],

  /* system */
  uname: OK, hostname: OK, hostnamectl: OK, uptime: OK, whoami: OK, id: OK, w: OK, who: OK, last: OK, lastlog: OK,
  date: OK, cal: OK, timedatectl: OK, lscpu: OK, lspci: OK, lsusb: OK, lsmod: OK, lsmem: OK, free: OK,
  vmstat: OK, iostat: OK, mpstat: OK, sar: OK, dmesg: OK, journalctl: OK, arch: OK, nproc: OK,
  tty: [["0", "Standard input is a terminal"], ["1", "Standard input is not a terminal"], ["2", "An error occurred"]],
  stty: OK, lsb_release: OK, inxi: OK
});

window.ENVVARS = Object.assign(window.ENVVARS || {}, {
  ls: [
    ["LS_COLORS", "Color scheme for file types (generated by dircolors)"],
    ["QUOTING_STYLE", "Default quoting style for output names"],
    ["COLUMNS", "Terminal width used for multicolumn output"],
    ["TIME_STYLE", "Default timestamp format for long listings"]
  ],
  tree: [
    ["LS_COLORS", "Color scheme used when color output is enabled"]
  ],
  file: [
    ["MAGIC", "Colon-separated list of extra magic database files"]
  ],
  less: [
    ["LESS", "Default options passed to less on every invocation"],
    ["LESSCHARSET", "Character set to assume (e.g. utf-8)"],
    ["LESSOPEN", "Input preprocessor command for filtering files"],
    ["LESSCLOSE", "Postprocessor command run after viewing"],
    ["EDITOR / VISUAL", "Editor started by the v command"]
  ],
  more: [
    ["MORE", "Default options for more"]
  ],
  date: [
    ["TZ", "Timezone used to display the date, overriding the system setting"]
  ]
});
