/* Indonesian content overlay — part 2 (process, network, users, packages) */
window.IDTXT = Object.assign(window.IDTXT || {}, {
});

Object.assign(window.IDTXT, {
  ps: { d: "Melaporkan snapshot proses saat ini.", d2: "Melaporkan snapshot proses yang sedang berjalan. Flag gaya BSD (ps aux) dan gaya UNIX (ps -ef) keduanya bekerja, plus keluaran kustom dengan -o.", o: ["Tampilkan semua proses semua pengguna dengan statistik CPU/MEM (gaya BSD)", "Tampilkan semua proses dalam format lengkap (gaya UNIX)", "Kolom keluaran kustom, mis. pid,ppid,%cpu,cmd", "Pilih berdasarkan daftar process ID", "Pilih berdasarkan nama atau ID pengguna efektif", "Gambar pohon proses ASCII art"], n: ["Semua proses, gaya BSD", "Pohon proses, gaya UNIX", "Satu pengguna, kolom pilihan", "Kasus: konsumen memori teratas", "Kasus: nama shell saat ini"], s: ["Sukses", "Terjadi kesalahan"] },
  top: { d: "Menampilkan proses berjalan dan penggunaan sumber daya secara real time.", d2: "Tampilan langsung yang terus diperbarui, mengurutkan proses berdasarkan penggunaan CPU atau memori, dengan ringkasan beban, CPU, dan memori seluruh sistem di atas.", o: ["Sortir berdasarkan field yang disebut, mis. -o %MEM", "Pantau hanya process ID yang diberikan", "Pantau hanya proses milik pengguna itu", "Mode batch untuk skrip (tanpa interaksi)", "Jeda antar pembaruan layar"], n: ["Ringkasan proses langsung", "Sortir berdasarkan memori", "Amati satu PID", "Kasus: snapshot sekali jalan untuk skrip"], s: ["Sukses", "Terjadi kesalahan"] },
  htop: { d: "Penampil proses interaktif dan berwarna.", d2: "Penampil proses interaktif dan berwarna dengan dukungan mouse, meter per-CPU, serta kill/renice yang mudah — pengganti modern untuk top.", o: ["Tampilkan proses dalam tampilan pohon secara bawaan", "Tampilkan hanya proses pengguna yang diberikan", "Tampilkan hanya PID yang diberikan", "Atur jeda antar pembaruan dalam sepersepuluh detik"], n: ["Penampil interaktif", "Hanya satu pengguna", "Tampilan pohon secara bawaan"], s: ["Sukses", "Terjadi kesalahan"] },
  kill: { d: "Mengirim sinyal (mis. terminate) ke proses berdasarkan PID.", d2: "Mengirim sinyal ke proses berdasarkan PID. Bawaannya SIGTERM (permintaan sopan untuk keluar); SIGKILL (9) tidak dapat ditangkap dan memaksa penghentian.", o: ["Tentukan sinyal yang dikirim, dengan nama atau nomor", "List nama dan nomor sinyal", "Matikan seketika; proses tidak dapat bersih-bersih", "Minta proses berhenti dengan anggun (bawaan)", "Hangup; banyak daemon memuat ulang konfigurasi karenanya"], n: ["Minta PID 1234 berhenti (SIGTERM)", "Matikan paksa proses yang macet", "Kasus: suruh daemon memuat ulang konfigurasinya", "List nama dan nomor sinyal"], s: ["Semua sinyal berhasil dikirim", "Setidaknya satu sinyal tidak dapat dikirim"] },
  killall: { d: "Mematikan proses berdasarkan nama persis.", d2: "Mengirim sinyal ke setiap proses yang berjalan dengan nama perintah persis yang diberikan. Gunakan pkill bila Anda memerlukan pencocokan pola.", o: ["Minta konfirmasi sebelum mematikan", "Matikan hanya proses milik pengguna yang diberikan", "Tunggu sampai semua proses yang dimatikan mati", "Pilih sinyal (bawaan TERM)"], n: ["Matikan semua proses firefox", "Hanya proses python milik bob", "Tunggu sampai proses-prosesnya hilang"], s: ["Setidaknya satu proses yang cocok dikirimi sinyal", "Tidak ada proses yang cocok (atau kegagalan lain)"] },
  pkill: { d: "Mengirim sinyal ke proses yang cocok dengan nama atau pola.", d2: "Mengirim sinyal ke proses yang dipilih berdasarkan pola nama dan atribut lain (pengguna, terminal, induk) — kill dengan pencocokan ala grep.", o: ["Cocokkan pola terhadap baris perintah lengkap", "Pilih hanya proses yang pengguna efektifnya cocok", "Kirim SIGKILL alih-alih SIGTERM", "Pilih hanya proses cocok yang terbaru", "Wajibkan kecocokan persis nama proses"], n: ["Kasus: cocokkan baris perintah lengkap", "Semua proses node milik alice", "Kirim SIGHUP ke proses yang cocok"], s: ["Satu atau lebih proses cocok", "Tidak ada proses yang cocok", "Kesalahan sintaks pada baris perintah", "Kesalahan fatal"] },
  nice: { d: "Menjalankan program dengan prioritas penjadwalan yang diubah.", d2: "Menjalankan perintah dengan prioritas penjadwalan yang disesuaikan. Niceness lebih tinggi (hingga 19) mengalahkan CPU ke proses lain; nilai negatif mengambil lebih banyak dan memerlukan root.", o: ["Tambahkan N ke niceness (bawaan 10)", "Tampilkan bantuan lalu keluar"], n: ["Jalankan dengan prioritas lebih rendah", "Prioritas lebih tinggi (perlu root)", "Kasus: cegah backup melahap CPU"], s: ["nice sendiri gagal", "Perintah ditemukan tapi tidak dapat dijalankan", "Perintah tidak ditemukan", "Status keluaran perintah"] },
  renice: { d: "Mengubah prioritas proses yang sedang berjalan.", d2: "Mengubah prioritas penjadwalan satu atau lebih proses, pengguna, atau grup proses yang berjalan tanpa menghentikannya.", o: ["Tentukan nilai niceness baru", "Artikan argumen sebagai process ID (bawaan)", "Artikan argumen sebagai nama pengguna atau UID", "Artikan argumen sebagai process group ID"], n: ["Turunkan prioritas job yang berjalan", "Kasus: semua proses alice sekaligus"], s: ["Sukses", "Terjadi kesalahan"] },
  nohup: { d: "Menjalankan perintah kebal hangup, keluaran ke berkas.", d2: "Menjalankan perintah kebal sinyal hangup sehingga tetap berjalan setelah Anda logout; keluaran masuk nohup.out kecuali dialihkan. Biasanya digabung dengan & untuk menjalankan di latar belakang.", o: ["Tampilkan bantuan lalu keluar", "Tampilkan informasi versi lalu keluar"], n: ["Bertahan setelah logout, keluaran ke nohup.out", "Kasus: log kustom, termasuk error"], s: ["Status keluaran perintah yang dijalankan di bawah nohup"], v: ["Lokasi berkas keluaran nohup.out bawaan"] },
  bg: { d: "Melanjutkan job yang terhenti di latar belakang.", d2: "Melanjutkan job yang terhenti (Ctrl-Z) di latar belakang, seolah dimulai dengan &.", o: ["Lanjutkan job dengan id yang diberikan, mis. %1 (bawaan: job saat ini)"], n: ["Lanjutkan job yang terhenti di latar belakang", "Lanjutkan job nomor 2"], s: ["Sukses", "Job tidak ada, atau terjadi kesalahan"] },
  fg: { d: "Membawa job ke latar depan.", d2: "Membawa job yang di-latar-belakangkan atau terhenti ke latar depan, menghubungkannya kembali ke terminal.", o: ["Pilih job, mis. %1 (bawaan: job saat ini)"], n: ["Bawa job ke latar depan", "Job 1 ke latar depan"], s: ["Sukses", "Job tidak ada, atau terjadi kesalahan"] },
  jobs: { d: "Me-list job aktif shell beserta statusnya.", d2: "Me-list job yang dimulai dari shell saat ini beserta statusnya (Running, Stopped) dan id job (%1, %2).", o: ["List process ID di samping informasi normal", "List hanya process ID", "Batasi keluaran ke job yang berjalan", "Batasi keluaran ke job yang terhenti"], n: ["List job shell ini", "Sertakan PID", "Hanya yang berjalan"], s: ["Sukses"] },
  disown: { d: "Menghapus job dari tabel job shell agar bertahan setelah logout.", d2: "Menghapus job dari tabel job shell (atau menandainya mengabaikan SIGHUP) sehingga bertahan setelah shell keluar — penyelamat bagi job yang dimulai tanpa nohup.", o: ["Tandai job agar tidak menerima SIGHUP, tetapi tetap di tabel", "Disown semua job", "Disown hanya job yang berjalan"], n: ["Kasus: job bertahan setelah shell keluar", "Tetap di daftar, tapi abaikan SIGHUP", "Disown semua job"], s: ["Sukses", "Job tidak ada, atau terjadi kesalahan"] },
  time: { d: "Mengukur berapa lama sebuah perintah berjalan.", d2: "Menjalankan perintah dan melaporkan waktu real (jam dinding), user, dan system CPU yang dikonsumsinya.", o: ["Gunakan format keluaran kustom (GNU time)", "Gunakan format keluaran portabel", "Verbose: laporkan juga penggunaan memori (GNU time)"], n: ["Kasus: berapa lama build berlangsung?", "Cek kewarasan: real vs user/sys time", "Simpan pewaktuan ke berkas"], s: ["Perintah ditemukan tapi tidak dapat dijalankan", "Perintah tidak ditemukan", "Status keluaran perintah"] },
  timeout: { d: "Menjalankan perintah dengan batas waktu, mematikannya bila terlampaui.", d2: "Menjalankan perintah dan mematikannya bila masih berjalan setelah durasi yang diberikan, keluar dengan status 124 — jaring pengaman bagi skrip yang bisa macet.", o: ["Kirim sinyal ini alih-alih TERM saat waktu habis", "Kirim KILL bila proses masih hidup selama ini setelah sinyal pertama", "Keluar dengan status perintah bahkan saat timeout", "s detik (bawaan), m menit, h jam, d hari"], n: ["Matikan setelah 30 detik", "KILL keras setelah 5 menit", "TERM pada 30 s, KILL 10 s kemudian", "Kasus: probe keterjangkauan cepat"], s: ["Perintah kena timeout", "timeout sendiri gagal", "Perintah ditemukan tapi tidak dapat dijalankan", "Perintah tidak ditemukan", "Perintah dikirimi SIGKILL (128 + 9)", "Status keluaran perintah"] },
  watch: { d: "Menjalankan perintah berulang kali dan menampilkan keluarannya.", d2: "Menjalankan perintah berulang (bawaan setiap 2 s) dalam tampilan layar penuh, sempurna untuk memantau keluaran seperti df -h atau status layanan.", o: ["Detik antar pembaruan (pecahan diperbolehkan)", "Sorot perubahan antar pembaruan", "Matikan header yang menampilkan perintah dan interval", "Keluar saat keluaran yang terlihat berubah"], n: ["Kasus: penggunaan disk, disegarkan setiap detik", "Sorot apa yang berubah", "Keluar saat keluaran berubah"], s: ["Berakhir normal", "Terjadi kesalahan"] },
  pstree: { d: "Menampilkan proses yang berjalan sebagai pohon.", d2: "Menggambar proses yang berjalan sebagai pohon berakar di init/systemd, memperlihatkan hubungan induk-anak; subtree identik diringkas dengan hitungan.", o: ["Tampilkan PID (sekaligus mematikan peringkasan)", "Tampilkan perubahan UID saat pengguna proses berbeda", "Tampilkan argumen baris perintah", "Tampilkan rantai induk proses yang diberikan"], n: ["Pohon keluarga proses", "Pohon satu pengguna dengan PID", "Kasus: rantai leluhur satu proses"], s: ["Sukses", "Terjadi kesalahan"] },
  pidof: { d: "Menemukan process ID program yang berjalan.", d2: "Mencetak process ID semua instance yang berjalan dari program yang disebut; dipakai intensif oleh skrip init.", o: ["Kembalikan hanya satu PID", "Cocokkan juga skrip dengan nama yang diberikan", "Lewati PID yang diberikan (atau %PPID untuk induk)"], n: ["PID daemon sshd", "Hanya satu PID"], s: ["Setidaknya satu proses yang cocok ditemukan", "Tidak ada proses yang cocok"] },
  pidstat: { d: "Melaporkan statistik proses individual.", d2: "Melaporkan statistik per proses dari /proc: CPU (-u), memori (-r), I/O (-d), context switch (-w) untuk task yang dipilih atau semuanya.", o: ["Laporkan penggunaan CPU (bawaan)", "Laporkan paging dan penggunaan memori", "Laporkan statistik I/O (kB dibaca/ditulis per detik)", "Pantau PID yang diberikan atau semua task"], n: ["CPU per proses setiap 2 s", "I/O disk satu proses", "Kasus: memori/paging, lima sampel"], s: ["Sukses", "Terjadi kesalahan"] },
  strace: { d: "Menelusuri system call dan sinyal suatu proses.", d2: "Mencegat dan merekam system call yang dibuat program serta sinyal yang diterimanya — perkakas pamungkas untuk mendebug 'kenapa ini gagal?' (open, stat, connect...).", o: ["Tempel ke proses berjalan dengan PID yang diberikan", "Ikuti proses anak saat mereka dibuat", "Telusuri hanya syscall yang disebut, mis. -e trace=network", "Hitung waktu, panggilan, dan error per syscall", "Tulis trace ke berkas alih-alih stderr"], n: ["Syscall suatu perintah dan anak-anaknya", "Tempel ke proses berjalan", "Hanya syscall jaringan", "Kasus: histogram waktu syscall", "Simpan trace lengkap untuk analisis"], s: ["Status keluaran program yang ditelusuri"] },
  ltrace: { d: "Menelusuri panggilan pustaka yang dibuat program.", d2: "Menjalankan program sambil mencegat panggilannya ke pustaka bersama (seperti malloc atau strcmp), melengkapi strace yang menelusuri panggilan kernel.", o: ["Tempel ke proses berjalan dengan PID yang diberikan", "Telusuri juga proses anak", "Tampilkan hanya panggilan ke fungsi dari pustaka yang diberikan", "Cetak ringkasan statistik alih-alih trace"], n: ["Panggilan pustaka suatu program", "Ringkasan waktu panggilan pustaka", "Kasus: amati satu fungsi"], s: ["Status keluaran program yang ditelusuri"] },
  exec: { d: "Menggantikan proses shell saat ini dengan sebuah perintah.", d2: "Menggantikan proses shell saat ini dengan perintah yang diberikan — tanpa PID baru, dan perintah mewarisi file descriptor shell. Umum sebagai PID 1 dalam container.", o: ["Awali argv[0] perintah yang dieksekusi dengan tanda hubung (perilaku login shell)", "Jalankan perintah dengan lingkungan kosong", "Alihkan semua keluaran shell berikutnya ke file"], n: ["Kasus: alihkan semua yang dicetak shell ini", "Kasus: ganti shell sebagai PID 1 dalam container", "Baca stdin dari berkas"], s: ["Menggantikan shell; status keluaran adalah status perintah yang dieksekusi"] },
  ulimit: { d: "Mengambil atau mengatur batas sumber daya untuk shell dan anaknya.", d2: "Mengambil atau mengatur batas sumber daya untuk shell dan proses yang dimulainya: berkas terbuka, maksimal proses, ukuran stack, ukuran core dump.", o: ["Tampilkan semua batas saat ini", "Atur/tampilkan jumlah maksimum file descriptor terbuka", "Atur/tampilkan jumlah maksimum proses pengguna", "Operasikan pada hard limit", "Operasikan pada soft limit (bawaan)"], n: ["Semua batas saat ini", "Kasus: naikkan batas berkas terbuka untuk shell ini", "Maksimal proses pengguna"], s: ["Sukses", "Terjadi kesalahan"] },
  trap: { d: "Menangkap sinyal atau kejadian exit dalam skrip shell.", d2: "Mengatur agar shell menjalankan perintah saat sinyal tiba atau saat shell keluar — dasar handler pembersihan dalam skrip.", o: ["Cetak daftar nama dan nomor sinyal", "Cetak perintah trap yang terkait dengan setiap sinyal", "Abaikan sinyal", "Kembalikan sinyal ke penanganan bawaannya"], n: ["Kasus: bersihkan berkas temp saat keluar", "Abaikan Ctrl-C", "Pulihkan penanganan Ctrl-C bawaan", "Bereaksi terhadap sinyal kustom"], s: ["Sukses", "Terjadi kesalahan"] },
  lsof: { d: "Me-list berkas, socket, dan pipe terbuka per proses.", d2: "Me-list berkas terbuka — berkas biasa, socket, pipe, perangkat — dan proses yang memegangnya. Cara klasik mencari tahu apa yang memakai sebuah port atau filesystem yang ter-mount.", o: ["List proses yang memakai port jaringan, mis. -i :80", "List berkas jaringan suatu protokol, mis. -i tcp", "List berkas yang dibuka pengguna yang diberikan", "List berkas yang dibuka PID yang diberikan", "List berkas terbuka di bawah direktori secara rekursif", "Lewati resolusi nama host/port (keluaran lebih cepat)"], n: ["Kasus: siapa yang mendengarkan di port 80?", "Berkas yang dibuka satu pengguna", "Semua yang terbuka di bawah direktori", "Kasus: kenapa umount bilang 'device busy'?", "Berkas terbuka satu proses"], s: ["Sukses", "Terjadi kesalahan"] }
});

Object.assign(window.IDTXT, {
  ping: { d: "Menguji keterjangkauan host dan mengukur latensi.", d2: "Mengirim paket ICMP ECHO_REQUEST ke host dan melaporkan waktu bolak-balik setiap balasan, memverifikasi keterjangkauan serta mengukur latensi dan kehilangan paket.", o: ["Berhenti setelah mengirim count paket", "Detik antar paket (pecahan dengan root)", "Atur ukuran payload dalam byte", "Waktu menunggu respons, dalam detik", "Paksa IPv4 atau IPv6"], n: ["Empat ping lalu berhenti", "Probe cepat (perlu root)", "Kasus: uji MTU path tanpa fragmentasi"], s: ["Setidaknya satu respons diterima", "Tidak ada respons yang diterima", "Terjadi kesalahan"] },
  ip: { d: "Menampilkan dan memanipulasi routing, perangkat, dan alamat (modern).", d2: "Perkakas modern untuk konfigurasi jaringan: alamat (ip a), route (ip r), link (ip l), neighbor, dan tunnel. Menggantikan ifconfig, route, dan arp.", o: ["Tampilkan atau ubah alamat: ip a, ip addr add 10.0.0.5/24 dev eth0", "Tampilkan atau ubah tabel routing: ip route add default via ...", "Tampilkan atau ubah antarmuka: ip link set eth0 up", "Tambah statistik (error, drop) ke keluaran", "Keluaran pendek satu baris per item"], n: ["Alamat di semua antarmuka", "Tabel routing dan gateway bawaan", "Naikkan antarmuka", "Tambah alamat IP", "Kasus: ringkasan alamat kompak"], s: ["Sukses", "Terjadi kesalahan"] },
  ifconfig: { d: "Mengonfigurasi antarmuka jaringan (legacy).", d2: "Mengonfigurasi atau menampilkan antarmuka jaringan cara legacy. Masih umum di dokumentasi dan tutorial lama, tetapi ip adalah pengganti modernnya.", o: ["Aktifkan atau nonaktifkan antarmuka", "Atur network mask", "Atur alamat IP antarmuka", "Tampilkan semua antarmuka, termasuk yang down"], n: ["Ringkasan antarmuka (legacy)", "Aktifkan antarmuka", "Kasus: hanya alamat IP-nya"], s: ["Sukses", "Terjadi kesalahan"] },
  netstat: { d: "Menampilkan koneksi jaringan, port, dan statistik (legacy).", d2: "Menampilkan koneksi jaringan, port yang mendengarkan, tabel routing, dan statistik antarmuka. Digantikan oleh ss dan ip pada sistem modern.", o: ["Tampilkan socket TCP", "Tampilkan socket UDP", "Tampilkan hanya socket yang mendengarkan", "Tampilkan alamat dan port numerik (tanpa lookup DNS)", "Tampilkan PID dan program pemilik setiap socket", "Tampilkan tabel routing"], n: ["Kasus: semua port yang mendengarkan beserta pemiliknya", "Tabel routing, numerik", "Statistik protokol"], s: ["Sukses", "Terjadi kesalahan"] },
  ss: { d: "Menampilkan statistik socket (netstat modern).", d2: "Meng-dump statistik socket langsung dari kernel — pengganti netstat yang cepat dan modern. Pola flag populer yang sama: ss -tulpn.", o: ["Tampilkan socket TCP", "Tampilkan socket UDP", "Tampilkan socket yang mendengarkan", "Jangan resolusikan nama layanan", "Tampilkan proses yang memakai setiap socket", "Cetak statistik ringkasan", "Saring berdasarkan state, mis. state established"], n: ["Kasus: socket listening beserta prosesnya", "Koneksi TCP established", "Hitungan ringkasan socket", "Koneksi ke satu host"], s: ["Sukses", "Terjadi kesalahan"] },
  curl: { d: "Mentransfer data dari atau ke server lewat URL.", d2: "Mentransfer data dari atau ke server memakai sintaks URL, mendukung HTTP(S), FTP, dan banyak protokol lain — klien HTTP baris perintah standar.", o: ["Simpan berkas dengan nama remote-nya", "Tulis keluaran ke berkas yang diberikan", "Mode senyap: tanpa meter kemajuan, tanpa error", "Ambil hanya header HTTP (request HEAD)", "Ikuti redirect HTTP", "Gunakan metode HTTP tertentu, mis. -X POST", "Kirim data dalam request POST (form-encoded)", "Tambah header request kustom"], n: ["Unduh dengan nama remote", "Kasus: panggilan API senyap dipipe ke jq", "Hanya header", "Ikuti redirect ke berkas", "POST data form", "Request terautentikasi"], s: ["Sukses", "Tidak dapat meresolusi host", "Gagal terhubung ke host", "Halaman HTTP tidak diambil (dengan -f)", "Operasi timeout", "Kode error terdokumentasi lainnya"], v: ["Server proxy untuk merutekan request", "Host berpemisah koma yang melewati proxy", "Direktori tempat curl mencari konfigurasi .curlrc", "Sertifikat CA tambahan / direktori untuk verifikasi TLS"] },
  wget: { d: "Mengunduh berkas dari web secara non-interaktif.", d2: "Mengunduh berkas dari web secara non-interaktif, dengan mirroring rekursif, dukungan resume, dan timestamping untuk sinkronisasi inkremental.", o: ["Lanjutkan berkas yang terunduh sebagian", "Tulis ke berkas yang diberikan alih-alih nama remote", "Unduh secara rekursif (gabungkan dengan -np: no parents)", "Matikan semua keluaran", "Pindah ke latar belakang setelah dimulai", "Batasi kecepatan unduh, mis. 200k"], n: ["Kasus: lanjutkan unduhan yang terputus", "Senyap, nama keluaran kustom", "Mirror sebagian dokumentasi secara offline", "Jangan melahap koneksi"], s: ["Tidak ada masalah", "Kode error generik", "Error parse (mis. opsi)", "Error I/O berkas", "Kegagalan jaringan", "Kegagalan verifikasi SSL", "Kegagalan autentikasi nama pengguna/kata sandi", "Error protokol", "Server memberikan respons error"], v: ["Server proxy untuk merutekan request", "Host berpemisah koma yang melewati proxy", "Lokasi berkas konfigurasi wgetrc pengguna"] },
  ssh: { d: "Masuk dan menjalankan perintah di mesin remote dengan aman.", d2: "Mengenkripsi sesi login remote lewat jaringan. Juga menunnel koneksi TCP (-L) dan menjalankan perintah remote sekali jalan (ssh host cmd).", o: ["Gunakan berkas private key yang diberikan", "Hubungkan ke port yang diberikan (bawaan 22)", "Teruskan port lokal ke layanan remote", "Jangan jalankan perintah remote (khusus tunnel)", "Paksa alokasi pseudo-terminal", "Mode verbose (v lebih banyak = detail lebih banyak)"], n: ["Login interaktif", "Masuk dengan key tertentu", "Kasus: jalankan satu perintah remote", "Kasus: tunnel database remote ke localhost", "Port non-standar"], s: ["ssh sendiri gagal (koneksi atau autentikasi)", "Status keluaran perintah remote"], v: ["Socket untuk menghubungi agen autentikasi SSH", "Program GUI yang dipanggil untuk menanyakan passphrase", "Dipakai untuk penerusan X11 bila diset", "Diset oleh server di sisi remote: IP/port klien, IP/port server / terminal yang dialokasikan"] },
  scp: { d: "Menyalin berkas antar host lewat SSH.", d2: "Menyalin berkas antar host lewat koneksi SSH terenkripsi, memakai autentikasi dan opsi yang sama dengan ssh.", o: ["Salin direktori secara rekursif", "Gunakan berkas private key yang diberikan", "Hubungkan ke port yang diberikan (huruf besar P di sini)", "Aktifkan kompresi", "Pertahankan waktu modifikasi dan mode"], n: ["Unggah satu berkas", "Unduh satu berkas", "Salin sebuah pohon", "Kasus: kompresi selama transfer"], s: ["Sukses", "Terjadi kesalahan"], v: ["Socket untuk menghubungi agen autentikasi SSH", "Program GUI yang dipanggil untuk menanyakan passphrase"] },
  sftp: { d: "Sesi transfer berkas aman yang interaktif.", d2: "Membuka sesi interaktif mirip ftp lewat SSH dengan perintah seperti get, put, ls, dan cd — berguna bila model sekali-jalan scp terlalu kaku.", o: ["Hubungkan ke port yang diberikan", "Gunakan berkas private key yang diberikan", "Jalankan perintah dari berkas secara non-interaktif", "Aktifkan kompresi"], n: ["Sesi interaktif (get/put/ls)", "Kasus: transfer batch dari skrip"], s: ["Sukses", "Terjadi kesalahan", "Kegagalan koneksi SSH"], v: ["Socket untuk menghubungi agen autentikasi SSH"] },
  rsync: { d: "Transfer dan sinkronisasi berkas yang cepat dan inkremental.", d2: "Menyinkronkan berkas dan direktori dengan hanya mentransfer perbedaan — cepat untuk backup dan mirror. Bekerja secara lokal atau lewat SSH. Perhatikan semantik slash di akhir.", o: ["Mode arsip: rekursif, mempertahankan izin, waktu, link", "Tingkatkan verbosity", "Kompres data selama transfer", "Hapus berkas di tujuan yang hilang di sumber", "Tunjukkan apa yang akan dilakukan tanpa melakukannya", "Sama dengan --partial --progress: dapat dilanjutkan dengan progress bar"], n: ["Kasus: backup inkremental lewat SSH", "Mirror persis, membuang berkas basi", "Dapat dilanjutkan dengan progress bar", "Dry run: apa yang akan berubah?", "Sinkron tanpa .git"], s: ["Sukses", "Transfer parsial (sebagian berkas tak dapat dikirim)", "Berkas sumber hilang selama transfer", "Timeout pada kirim/terima data", "Kode error terdokumentasi lainnya"], v: ["Shell remote yang dipakai alih-alih ssh (mis. 'ssh -p 2222')", "Server proxy untuk koneksi daemon rsync", "Kata sandi untuk modul rsync:// terautentikasi"] },
  nc: { d: "Netcat: membaca dan menulis koneksi TCP/UDP.", d2: "Netcat membaca dan menulis data lewat koneksi TCP atau UDP — uji port, transfer berkas, mendengarkan sebagai server, atau debug protokol dengan tangan.", o: ["Pindai tanpa mengirim data (cek port)", "Verbose: laporkan apa yang terjadi", "Mode listen: berperan sebagai server", "Tentukan port sumber lokal", "Gunakan UDP alih-alih TCP", "Timeout untuk koneksi dan pembacaan akhir"], n: ["Kasus: apakah port remote terbuka?", "Kirim berkas ke siapa pun yang terhubung", "Terima di sisi lain", "Dengarkan di UDP"], s: ["Sukses", "Gagal"] },
  nmap: { d: "Eksplorasi jaringan dan pemindaian port keamanan.", d2: "Memindai host dan jaringan untuk menemukan mesin hidup, port terbuka, dan layanan yang berjalan (-sV) — perkakas standar inventaris jaringan dan audit keamanan.", o: ["Pindai hanya port yang diberikan, mis. -p 22,80,443 atau 1-1000", "Probing port terbuka untuk menentukan layanan/versi", "Pemindaian siluman TCP SYN (perlu root)", "Aktifkan deteksi OS", "Agresif: OS + versi + skrip + traceroute", "Lewati penemuan host; anggap semua host online"], n: ["Cek port tertentu", "Deteksi layanan dan versi", "Kasus: pindai LAN secara siluman", "Hanya penemuan host (ping scan)"], s: ["Sukses", "Kode error terdokumentasi (mis. tanpa target, kegagalan pemindaian)"] },
  traceroute: { d: "Menampilkan rute yang dilalui paket ke sebuah host.", d2: "Menampilkan jalur (router) yang dilalui paket untuk mencapai host, dengan waktu bolak-balik per hop — untuk melokalisasi di mana latensi atau kehilangan muncul.", o: ["Jangan resolusikan hostname (lebih cepat)", "Atur jumlah hop maksimum", "Gunakan ICMP ECHO alih-alih UDP", "Jumlah probe per hop (bawaan 3)"], n: ["Rute ke host", "Lewati lookup DNS (lebih cepat)", "Gunakan probe ICMP"], s: ["Sukses", "Terjadi kesalahan"] },
  mtr: { d: "Menggabungkan traceroute dan ping menjadi diagnostik jaringan langsung.", d2: "Menggabungkan traceroute dan ping, terus-menerus memprobing setiap hop pada rute dan menampilkan statistik loss dan latensi secara langsung.", o: ["Mode report: cetak statistik lalu keluar", "Berhenti setelah count probe", "Jangan resolusikan hostname", "Paksa IPv4 atau IPv6"], n: ["Kasus: laporan 100 probe, lalu keluar", "Loss dan latensi per hop secara langsung"], s: ["Sukses", "Terjadi kesalahan"] },
  dig: { d: "Meng-query name server DNS untuk record.", d2: "Meng-query server DNS untuk tipe record apa pun (A, AAAA, MX, TXT, NS...) dengan kontrol penuh dan jawaban detail — perkakas debug DNS standar.", o: ["Cetak hanya jawaban esensial", "Telusuri delegasi dari server root ke bawah", "Query ke server DNS tertentu, mis. @8.8.8.8", "Lookup balik untuk alamat IP", "Tipe record yang di-query: A, AAAA, MX, TXT, NS, SOA..."], n: ["Record A, jawaban lengkap", "Hanya alamatnya", "Server mail", "Kasus: tanya resolver tertentu", "Ikuti delegasi dari root"], s: ["Sukses", "Error penggunaan, jaringan, atau server (mis. 9: tiada balasan dari server)"] },
  nslookup: { d: "Meng-query name server internet secara interaktif.", d2: "Meng-query DNS secara interaktif atau sekali jalan untuk alamat dan record; lebih sederhana daripada dig tetapi kurang detail. dig atau host biasanya lebih disukai.", o: ["Cari nama yang diberikan", "Gunakan server DNS yang diberikan untuk query", "Atur tipe record query, mis. -type=MX", "Alias untuk -type"], n: ["Resolusi sebuah nama", "Record mail", "Query ke server tertentu"], s: ["Sukses", "Tiada respons dari server yang diminta"] },
  host: { d: "Perkakas lookup DNS sederhana.", d2: "Perkakas lookup DNS sederhana yang mengonversi nama ke alamat dan sebaliknya, serta dapat mengambil record MX, NS, dan lainnya.", o: ["Tentukan tipe record, mis. -t MX", "Keluaran 'all' yang verbose", "Bandingkan record SOA antar server otoritatif", "Gunakan TCP untuk query"], n: ["Resolusi nama cepat", "Server mail", "Kasus: lookup balik"], s: ["Sukses", "Terjadi kesalahan"] },
  whois: { d: "Mencari informasi registrasi dan kepemilikan domain.", d2: "Meng-query basis data WHOIS untuk record registrasi domain atau IP: registrar, tanggal pembuatan dan kedaluwarsa, kontak, dan nameserver.", o: ["Hubungkan ke server WHOIS yang diberikan", "Sembunyikan disclaimer legal", "Hubungkan ke port yang diberikan"], n: ["Record registrasi", "Query ke registry tertentu"], s: ["Sukses", "Terjadi kesalahan"] },
  route: { d: "Menampilkan atau mengubah tabel routing IP (legacy).", d2: "Menampilkan atau memanipulasi tabel routing IP kernel cara legacy (route -n). Pengganti modernnya adalah ip route.", o: ["Tampilkan alamat numerik (tanpa resolusi DNS)", "Tambah route: route add -net ... gw ...", "Hapus route", "Gunakan keluaran verbose gaya netstat"], n: ["Tabel routing (legacy)", "Kasus: tambah route statis"], s: ["Sukses", "Terjadi kesalahan"] },
  arp: { d: "Menampilkan atau mengubah cache alamat IP-ke-MAC.", d2: "Menampilkan dan mengubah cache ARP kernel, yang memetakan alamat IP ke alamat MAC pada jaringan lokal. ip neigh adalah bentuk modernnya.", o: ["Tampilkan cache gaya BSD (semua entri)", "Tampilkan alamat numerik", "Hapus entri cache untuk sebuah alamat", "Tambah entri ARP statis"], n: ["Cache neighbor", "Keluaran numerik", "Hapus satu entri"], s: ["Sukses", "Terjadi kesalahan"] },
  ethtool: { d: "Meng-query dan mengontrol pengaturan driver dan perangkat keras jaringan.", d2: "Meng-query dan mengontrol pengaturan driver antarmuka jaringan: kecepatan link, duplex, autonegotiation, offload, dan ukuran ring buffer.", o: ["Tampilkan pengaturan antarmuka dan status link", "Tampilkan informasi driver dan firmware", "Tampilkan penghitung statistik khusus NIC", "Ubah pengaturan, mis. speed 1000 duplex full autoneg off"], n: ["Kecepatan link dan duplex", "Kunci pengaturan link", "Driver dan firmware", "Kasus: penghitung error NIC"], s: ["Sukses", "Terjadi kesalahan"] },
  tcpdump: { d: "Menangkap dan menganalisis paket jaringan.", d2: "Menangkap paket pada antarmuka dan mencetaknya dalam bentuk yang mudah dibaca atau menyimpannya ke berkas pcap untuk dianalisis di Wireshark. Filter memakai sintaks pcap.", o: ["Dengarkan di antarmuka yang diberikan (atau any)", "Tulis paket mentah ke berkas pcap", "Baca paket dari berkas pcap", "Jangan resolusikan hostname atau port", "Berhenti setelah count paket", "Cetak setiap paket sebagai ASCII (untuk debug HTTP)", "Mis. 'port 80', 'host 10.0.0.5', 'tcp and dst port 443'"], n: ["Amati trafik HTTP secara langsung", "Kasus: tangkap untuk Wireshark", "Putar ulang tangkapan sebagai ASCII", "Kasus: upaya koneksi masuk"], s: ["Sukses", "Terjadi kesalahan"] },
  iptables: { d: "Mengonfigurasi firewall kernel Linux legacy.", d2: "Mengonfigurasi firewall netfilter legacy: aturan dalam chain (INPUT, OUTPUT, FORWARD) yang menerima, membuang, atau me-NAT paket. nftables adalah penerus modernnya.", o: ["List aturan dalam chain (tambah -n untuk numerik, -v untuk penghitung)", "Tambahkan aturan, mis. -A INPUT -p tcp --dport 22 -j ACCEPT", "Hapus aturan", "Atur kebijakan bawaan chain", "Pilih tabel: filter (bawaan), nat, mangle, raw", "Target lompat: ACCEPT, DROP, REJECT, SNAT, DNAT, MASQUERADE"], n: ["List aturan dengan penghitung", "Izinkan SSH", "Blokir sebuah jaringan", "Kasus: NAT untuk routing"], s: ["Sukses", "Terjadi kesalahan"] },
  nft: { d: "Mengonfigurasi firewall netfilter modern (nftables).", d2: "Mengonfigurasi nftables, kerangka penyaringan paket kernel modern yang menggantikan iptables, dengan satu sintaks terpadu untuk filtering dan NAT.", o: ["Tampilkan konfigurasi aktif lengkap", "Buat tabel, mis. add table inet filter", "Buat chain dalam tabel", "Tambah aturan filtering/NAT ke chain", "Muat aturan dari berkas skrip"], n: ["Dump firewall aktif", "Buat tabel dasar", "Kasus: izinkan SSH"], s: ["Sukses", "Terjadi kesalahan"] },
  ufw: { d: "Uncomplicated Firewall: frontend sederhana untuk iptables.", d2: "Uncomplicated Firewall — frontend iptables/nftables yang ramah untuk Ubuntu/Debian, dirancang untuk aturan allow/deny sederhana pada satu host.", o: ["Nyalakan atau matikan firewall", "Tampilkan aturan dan status logging", "Izinkan trafik, mis. ufw allow 22 atau ufw allow ssh", "Buang atau tolak trafik yang cocok", "Atur kebijakan bawaan incoming/outgoing"], n: ["Buka SSH", "Nyalakan firewall", "Tampilkan aturan dan bawaan", "Kasus: blokir satu host"], s: ["Sukses", "Terjadi kesalahan"] },
  "firewall-cmd": { d: "Mengontrol daemon firewall firewalld.", d2: "Mengontrol firewalld, manajer firewall dinamis pada sistem Fedora/RHEL, memakai zona (public, trusted, ...) alih-alih aturan mentah.", o: ["Periksa apakah firewalld aktif", "Tampilkan layanan, port, dan aturan zona aktif", "Izinkan layanan, mis. http; tambah --permanent agar persisten", "Buka port, mis. 8080/tcp", "Muat ulang konfigurasi firewall"], n: ["Konfigurasi zona aktif", "Izinkan HTTP (persisten)", "Terapkan perubahan permanen", "Kasus: buka port sekarang juga"], s: ["Sukses", "Terjadi kesalahan"] },
  "ssh-keygen": { d: "Membuat dan mengelola pasangan kunci SSH.", d2: "Membuat, mengonversi, dan mengelola pasangan kunci SSH untuk autentikasi. Ed25519 adalah algoritma modern yang disarankan.", o: ["Tipe kunci: ed25519 (disarankan), rsa, ecdsa", "Ukuran kunci dalam bit (untuk RSA, pakai 4096)", "Berkas kunci yang ditulis/dibaca", "Lampirkan komentar, biasanya user@host", "Atur passphrase di baris perintah (kosong = tanpa)"], n: ["Pasangan kunci modern dengan bawaan", "RSA 4096-bit di path pilihan", "Tampilkan fingerprint sebuah kunci", "Kasus: lupakan host key lama"], s: ["Sukses", "Terjadi kesalahan"] },
  "ssh-copy-id": { d: "Memasang kunci publik Anda di server remote untuk login.", d2: "Menambahkan kunci publik Anda ke ~/.ssh/authorized_keys host remote sehingga login ssh berikutnya tidak memerlukan kata sandi.", o: ["Salin berkas identitas (kunci publik) yang diberikan", "Paksa: jangan periksa apakah kunci sudah ada", "Dry run: cetak kunci yang akan dipasang", "Hubungkan ke port yang diberikan"], n: ["Pasang kunci Anda untuk login tanpa kata sandi", "Pilih kunci mana yang dipasang"], s: ["Sukses", "Terjadi kesalahan"] },
  socat: { d: "Relai serbaguna untuk aliran data dua arah.", d2: "Membangun dua aliran byte dua arah dan menyalin di antaranya — hubungkan apa pun ke apa pun: TCP, UDP, socket UNIX, berkas, proses.", o: ["Dengarkan koneksi TCP (tambah ,fork untuk banyak)", "Buka koneksi klien TCP", "Hubungkan ke socket domain UNIX", "Jalankan program dan tempelkan ke aliran", "Gunakan stdin/stdout sebagai salah satu endpoint"], n: ["Kasus: proxy TCP sederhana", "Bicara ke socket UNIX", "Sesi HTTP manual"], s: ["Sukses", "Terjadi kesalahan"] },
  telnet: { d: "Terhubung ke layanan remote lewat TCP (tanpa enkripsi, legacy).", d2: "Membuka sesi TCP plaintext ke host dan port. Secara historis protokol login remote; kini kebanyakan dipakai untuk menguji apakah sebuah port TCP menjawab.", o: ["Hubungkan ke host dan port yang diberikan", "Paksa IPv4 atau IPv6", "Tentukan nama pengguna remote"], n: ["Kasus: probing port SMTP dengan tangan", "Mengobrol dengan Redis lokal"], s: ["Sukses", "Terjadi kesalahan"] }
});

Object.assign(window.IDTXT, {
  useradd: { d: "Membuat akun pengguna baru (level rendah).", d2: "Membuat akun pengguna dan memperbarui /etc/passwd, /etc/shadow, serta berkas grup. Sistem Debian biasanya lebih menyukai adduser yang lebih ramah.", o: ["Buat direktori home pengguna", "Atur login shell, mis. /bin/bash", "Tambahkan pengguna ke grup tambahan ini", "Atur field nama lengkap / komentar", "Pilih user ID tertentu", "Atur tanggal kedaluwarsa akun"], n: ["Akun dengan home dir dan bash", "Tambah grup tambahan", "Kasus: akun yang kedaluwarsa", "Akun sistem, tanpa login"], s: ["Sukses", "Berkas password tak dapat diperbarui", "Argumen tidak valid untuk opsi", "UID sudah dipakai", "Nama pengguna atau grup sudah dipakai", "Direktori home tak dapat dibuat"] },
  userdel: { d: "Menghapus akun pengguna dan, opsional, berkasnya.", d2: "Menghapus akun pengguna beserta entrinya dari berkas sistem; -r juga menghapus direktori home dan mail spool.", o: ["Hapus direktori home dan mail spool", "Paksa penghapusan walau pengguna sedang masuk", "Hapus pemetaan pengguna SELinux"], n: ["Hapus akun", "Hapus juga home dan mail", "Paksa, walau sedang masuk"], s: ["Sukses", "Berkas password tak dapat diperbarui", "Pengguna yang dimaksud tidak ada", "Pengguna sedang masuk", "Direktori home tak dapat dihapus"] },
  usermod: { d: "Mengubah akun pengguna yang ada.", d2: "Mengubah akun yang ada: ganti shell, direktori home, grup, kedaluwarsa, atau status kunci.", o: ["Tambahkan pengguna ke grup tambahan (selalu gunakan -a bersama -G)", "Ganti login shell", "Ganti direktori home (tambah -m untuk memindahkan isi)", "Kunci / buka kunci password", "Ganti nama akun"], n: ["Kasus: tambah ke grup (mempertahankan grup yang ada)", "Ganti login shell", "Kunci akun", "Pindahkan direktori home"], s: ["Sukses", "Berkas password tak dapat diperbarui", "Argumen tidak valid", "Grup yang dimaksud tidak ada", "Nama pengguna sudah dipakai", "Berkas grup tak dapat diperbarui"] },
  adduser: { d: "Pembuatan pengguna interaktif yang ramah (Debian/Ubuntu).", d2: "Skrip pembuatan pengguna interaktif yang ramah di Debian/Ubuntu: membuat direktori home, menyalin berkas skel, dan menanyakan kata sandi serta detail.", o: ["Buat akun tanpa kata sandi yang berfungsi (autentikasi berbasis kunci)", "Tambahkan pengguna ke GROUP sebagai grup awal", "Buat akun sistem (UID rendah, tanpa kata sandi)", "Lewati prompt informasi finger"], n: ["Interaktif: home, kata sandi, detail", "Akun layanan sistem", "Kasus: akun login khusus kunci"], s: ["Sukses", "Terjadi kesalahan"] },
  deluser: { d: "Menghapus pengguna atau grup (Debian/Ubuntu).", d2: "Padanan adduser di Debian/Ubuntu untuk menghapus pengguna dan grup, dengan opsi membersihkan berkas home dan mail.", o: ["Hapus direktori home dan mail spool", "Cadangkan berkas sebelum menghapusnya", "Hapus grup, bukan pengguna"], n: ["Hapus akun", "Akun beserta berkasnya", "Kasus: cadangkan home dir saat menghapus"], s: ["Sukses", "Terjadi kesalahan"] },
  groupadd: { d: "Membuat grup baru.", d2: "Membuat grup baru, memperbarui /etc/group (dan gshadow). Pengguna kemudian ditambahkan dengan usermod -aG atau gpasswd -a.", o: ["Gunakan group ID tertentu", "Buat grup sistem (GID di bawah 1000)", "Berhasil walau grup sudah ada"], n: ["Buat grup", "Dengan GID tertentu"], s: ["Sukses", "Argumen tidak valid untuk opsi", "GID sudah dipakai", "Nama grup sudah dipakai", "Berkas grup tak dapat diperbarui"] },
  groupdel: { d: "Menghapus grup.", d2: "Menghapus grup dari berkas sistem. Grup yang menjadi grup primer seorang pengguna tidak dapat dihapus.", o: ["Hapus grup walau menjadi grup primer", "Operasikan dalam direktori chroot"], n: ["Hapus grup", "Paksa, walau menjadi grup primer"], s: ["Sukses", "Grup yang dimaksud tidak ada", "Tidak dapat menghapus grup primer pengguna", "Berkas grup tak dapat diperbarui"] },
  groupmod: { d: "Mengubah definisi grup.", d2: "Mengubah definisi grup: mengganti namanya atau mengubah GID-nya.", o: ["Ganti nama grup", "Ubah group ID (berkas menyimpan GID lama sampai diperbaiki)"], n: ["Ganti nama grup", "Ubah GID"], s: ["Sukses", "Argumen tidak valid untuk opsi", "GID sudah dipakai", "Grup yang dimaksud tidak ada", "Nama grup sudah dipakai"] },
  groups: { d: "Menampilkan grup tempat seorang pengguna bergabung.", d2: "Menampilkan nama semua grup tempat pengguna bergabung — yang pertama adalah grup primer (login).", o: ["Tampilkan bantuan lalu keluar", "Tampilkan informasi versi lalu keluar"], n: ["Grup yang Anda ikuti", "Grup pengguna lain"], s: ["Sukses", "Terjadi kesalahan"] },
  newgrp: { d: "Masuk ke grup baru dalam sesi saat ini.", d2: "Memulai shell baru yang group ID efektifnya adalah grup yang disebut, sehingga berkas yang baru dibuat mendapat grup itu tanpa logout.", o: ["Simulasikan login penuh (reset lingkungan)", "Beralih ke grup yang disebut (harus anggota)"], n: ["Kasus: pakai grup baru tanpa login ulang", "Ganti grup dengan lingkungan segar"], s: ["Sukses", "Terjadi kesalahan"] },
  gpasswd: { d: "Mengadministrasi /etc/group (mengelola anggota grup).", d2: "Mengadministrasi /etc/group: menambah atau menghapus anggota serta mengatur administrator atau kata sandi grup.", o: ["Tambahkan pengguna ke grup", "Hapus pengguna dari grup", "Atur daftar anggota lengkap", "Atur daftar administrator grup"], n: ["Tambah anggota", "Hapus anggota", "Kasus: atur daftar anggota yang persis"], s: ["Sukses", "Terjadi kesalahan"] },
  passwd: { d: "Mengubah kata sandi pengguna.", d2: "Mengubah kata sandi pengguna dengan memperbarui entri shadow. Pengguna biasa hanya dapat mengubah miliknya sendiri; root dapat mengubah akun mana pun.", o: ["Kunci password akun", "Buka kunci password akun", "Kedaluwarsakan password, memaksa penggantian saat login berikut", "Hapus password (login tanpa kata sandi)", "Tampilkan informasi status password"], n: ["Ganti kata sandi Anda sendiri", "Ganti kata sandi orang lain", "Kunci akun", "Kasus: paksa penggantian saat login berikut"], s: ["Sukses", "Izin ditolak", "Kombinasi opsi tidak valid", "Argumen tidak valid untuk opsi", "Berkas password atau grup tak dapat diperbarui"] },
  chage: { d: "Mengubah informasi kedaluwarsa kata sandi pengguna.", d2: "Melihat dan mengubah kebijakan penuaan kata sandi: hari minimum/maksimum antar penggantian, periode peringatan, dan kedaluwarsa akun.", o: ["Tampilkan informasi penuaan akun", "Jumlah hari maksimum password berlaku", "Hari peringatan sebelum kedaluwarsa", "Tanggal akun kedaluwarsa (YYYY-MM-DD)"], n: ["Tampilkan penuaan kata sandi", "Kedaluwarsakan password setiap 90 hari", "Peringatkan seminggu sebelum kedaluwarsa"], s: ["Sukses", "Izin ditolak", "Sintaks tidak valid"] },
  chown: { d: "Mengubah pemilik dan grup berkas.", d2: "Mengubah pengguna pemilik dan/atau grup berkas. Dengan -R, menelusuri pohon direktori; perubahan kepemilikan memerlukan root.", o: ["Operasikan pada berkas dan direktori secara rekursif", "Ubah symlink-nya sendiri, bukan targetnya", "Laporkan hanya berkas yang kepemilikannya benar-benar berubah", "Gunakan pemilik/grup berkas R sebagai acuan"], n: ["Ganti pemilik", "Kasus: perbaiki web root secara rekursif", "Salin kepemilikan dari berkas lain"], s: ["Sukses", "Terjadi kesalahan"] },
  chgrp: { d: "Mengubah kepemilikan grup berkas.", d2: "Mengubah kepemilikan grup berkas — setengah grup saja dari chown.", o: ["Operasikan secara rekursif pada direktori", "Ubah symbolic link-nya sendiri", "Laporkan hanya berkas yang berubah", "Gunakan grup berkas R sebagai acuan"], n: ["Ganti grup", "Kasus: perubahan grup rekursif"], s: ["Sukses", "Terjadi kesalahan"] },
  chmod: { d: "Mengubah bit mode berkas (izin).", d2: "Mengubah bit izin berkas memakai mode oktal (755) atau ekspresi simbolik (u+x, go-w) untuk pemilik, grup, dan lainnya.", o: ["Ubah berkas dan direktori secara rekursif", "Laporkan hanya berkas yang benar-benar berubah", "Jelaskan setiap berkas yang diproses", "Oktal: 755, 644; simbolik: u+x, g-w, o=r, a+rX"], n: ["Pemilik rwx, lainnya rx", "Beri hanya pemilik hak eksekusi", "Tulis grup pada sebuah pohon", "Kasus: jadikan berkas privat"], s: ["Sukses", "Terjadi kesalahan"] },
  umask: { d: "Mengambil atau mengatur mask izin pembuatan berkas bawaan.", d2: "Menampilkan atau mengatur mask pembuatan berkas: bit izin yang dikurangkan dari bawaan (0666 berkas, 0777 direktori). 022 → berkas 644; 027 → terbaca grup, privat.", o: ["Atur mask, mis. umask 027", "Tampilkan mask secara simbolik, mis. u=rwx,g=rx,o=", "Cetak sebagai perintah shell yang dapat dipakai ulang"], n: ["Tampilkan mask saat ini", "Kasus: berkas baru privat untuk Anda dan grup Anda", "Tampilan simbolik: u=rwx,g=rx,o="], s: ["Sukses", "Mask atau opsi tidak valid"] },
  getent: { d: "Mengambil entri dari basis data sistem (passwd, group, hosts...).", d2: "Mengambil entri dari basis data name-service sistem (passwd, group, hosts, services) termasuk backend LDAP/NIS, memperlihatkan apa yang benar-benar diresolusi sistem.", o: ["Basis data yang di-query: passwd, group, hosts, ...", "Kunci opsional, mis. nama pengguna untuk passwd", "Batasi ke layanan tertentu dari nsswitch.conf"], n: ["Record pengguna seperti yang dilihat sistem", "Anggota grup", "Kasus: resolusi nama termasuk LDAP/hosts"], s: ["Entri ditemukan dan dicetak", "Kunci hilang, atau entri tidak ditemukan", "Sintaks tidak valid", "Enumerasi tidak didukung untuk basis data ini"] },
  su: { d: "Menjalankan shell sebagai pengguna lain atau root.", d2: "Menjalankan shell sebagai pengguna lain (bawaannya root). su - memulai login shell penuh dengan lingkungan target; su polos mempertahankan sebagian besar lingkungan Anda.", o: ["Mulai login shell dengan lingkungan pengguna target", "Jalankan satu perintah, lalu keluar", "Gunakan shell yang diberikan alih-alih milik target", "Pertahankan lingkungan saat ini"], n: ["Login shell root", "Menjadi alice dengan lingkungannya", "Kasus: satu perintah root, lalu kembali"], s: ["Sukses", "Kegagalan autentikasi atau eksekusi", "Status keluaran perintah (dengan -c)"], v: ["Direset agar cocok dengan akun pengguna target (kecuali -m dipakai)"] },
  sudo: { d: "Menjalankan perintah sebagai pengguna lain, biasanya root.", d2: "Menjalankan perintah sebagai root atau pengguna lain, sebagaimana diizinkan /etc/sudoers, dengan pencatatan audit lengkap atas apa yang dijalankan.", o: ["Simulasikan login awal sebagai pengguna target", "Jalankan perintah sebagai pengguna yang diberikan", "List perintah yang boleh Anda jalankan lewat sudo", "Jalankan shell sebagai pengguna target", "Batalkan kredensial ter-cache (paksa autentikasi ulang)", "Pertahankan lingkungan pengguna bila diizinkan"], n: ["Satu perintah sebagai root", "Login shell root penuh", "Kasus: jalankan sebagai pengguna non-root tertentu", "Apa yang boleh saya jalankan?", "Lupakan kredensial ter-cache saya"], s: ["Sukses", "Error sudo generik", "Perintah ditemukan tapi tidak dapat dijalankan", "Perintah tidak ditemukan", "Status keluaran perintah"], v: ["Diset untuk perintah: pengguna pemanggil, UID, dan GID", "Diset untuk perintah: perintah yang diminta sudo untuk dijalankan", "Editor yang dipakai sudoedit", "Program pembantu yang dipakai -A untuk membaca kata sandi"] },
  visudo: { d: "Menyunting berkas sudoers dengan aman beserta validasi.", d2: "Menyunting berkas sudoers dengan penguncian eksklusif dan validasi sintaks, mencegah berkas rusak mengunci semua orang dari root.", o: ["Sunting berkas yang diberikan alih-alih /etc/sudoers", "Hanya periksa berkas dari kesalahan sintaks", "Mode strict: keluhkan default yang tidak dikenal"], n: ["Sunting sudoers dengan aman", "Berkas drop-in untuk sebuah tim", "Hanya periksa sintaks"], s: ["Tidak ditemukan kesalahan sintaks", "Berkas sudoers mengandung kesalahan sintaks"], v: ["Editor yang dipakai untuk menyunting berkas sudoers"] },
  login: { d: "Memulai sesi pada sistem.", d2: "Memulai sesi baru pada sistem, menanyakan nama pengguna dan kata sandi. Normalmente dipanggil otomatis oleh getty pada konsol virtual.", o: ["Jangan reset lingkungan", "Lewati autentikasi (dipakai program lain)", "Catat nama host remote (login jaringan)"], n: ["Mulai sesi", "Masuk langsung sebagai alice"], s: ["Sukses", "Terjadi kesalahan"], v: ["Diset dari entri akun pengguna target saat login"] },
  logout: { d: "Keluar dari login shell.", d2: "Mengakhiri login shell, menutup sesi dan mengembalikan terminal ke prompt login.", o: ["Tampilkan bantuan lalu keluar", "Tampilkan informasi versi lalu keluar"], n: ["Akhiri login shell", "Kasus: padanannya di kebanyakan shell"], s: ["Sukses"] }
});

Object.assign(window.IDTXT, {
  apt: { d: "Manajer paket level tinggi untuk Debian/Ubuntu.", d2: "Antarmuka baris perintah yang disarankan untuk manajemen paket Debian/Ubuntu: instal, upgrade, cari, dan hapus paket dengan resolusi dependensi.", o: ["Segarkan indeks paket dari semua sumber", "Instal upgrade yang tersedia untuk semua paket", "Instal satu atau lebih paket", "Hapus paket (purge juga menghapus konfigurasinya)", "Cari nama dan deskripsi paket", "Tampilkan detail sebuah paket", "Hapus paket yang tak lagi dibutuhkan sebagai dependensi"], n: ["Kasus: segarkan indeks, lalu upgrade", "Instal beberapa paket", "Cari di katalog", "Detail paket", "Hapus paket beserta konfigurasinya", "Klaim kembali ruang dari dependensi lama"], s: ["Sukses", "Terjadi kesalahan"], v: ["Antarmuka yang dipakai skrip maintainer (mis. noninteractive)"] },
  "apt-get": { d: "Antarmuka baris perintah ke sistem paket Debian.", d2: "Perintah APT level rendah yang dirancang untuk skrip: operasi yang sama dengan apt dengan keluaran stabil dan ramah mesin.", o: ["Sinkronkan ulang berkas indeks paket", "Instal paket", "Anggap ya untuk semua prompt (skrip)", "Upgrade dengan penanganan dependensi cerdas", "Bersihkan paket tak terpakai dan berkas .deb ter-cache"], n: ["Kasus: instal tanpa pengawasan untuk skrip", "Upgrade dengan perubahan dependensi", "Hapus berkas .deb ter-cache"], s: ["Sukses", "Terjadi kesalahan"], v: ["Antarmuka yang dipakai skrip maintainer (mis. noninteractive)"] },
  aptitude: { d: "Frontend teks canggih untuk apt.", d2: "Frontend apt canggih dengan UI terminal layar penuh dan bahasa pencarian berbasis pola yang kuat; melacak paket terinstal otomatis dengan cermat.", o: ["Cari paket dengan bahasa pola aptitude", "Instal atau hapus paket", "Anggap ya untuk prompt", "(tanpa argumen) Mulai antarmuka interaktif layar penuh"], n: ["Pencarian pola yang kaya", "Instal dengan resolver yang lebih pintar", "Kasus: penelusur paket layar penuh"], s: ["Sukses", "Terjadi kesalahan"] },
  dpkg: { d: "Manajer paket Debian level rendah untuk berkas .deb.", d2: "Manajer paket Debian level rendah: menginstal, menghapus, dan memeriksa berkas .deb individual serta meng-query basis data paket terinstal. Tidak menyelesaikan dependensi (apt yang melakukannya).", o: ["Instal berkas paket .deb", "List paket terinstal yang cocok dengan pola", "List berkas yang dipasang oleh sebuah paket", "Cari paket pemilik sebuah berkas", "Hapus paket / purge termasuk konfigurasi", "Tampilkan status sebuah paket"], n: ["Instal .deb lokal", "Paket terinstal yang cocok dengan nama", "Kasus: paket mana pemilik berkas ini?", "Berkas yang dipasang oleh sebuah paket"], s: ["Sukses", "Terjadi kesalahan"], v: ["Antarmuka yang dipakai skrip maintainer (mis. noninteractive)"] },
  yum: { d: "Manajer paket untuk RHEL/CentOS 7 dan lebih lama.", d2: "Manajer paket rpm klasik pada RHEL/CentOS 7 dan sebelumnya, menangani instalasi, pembaruan, dan resolusi dependensi dari repositori yang dikonfigurasi.", o: ["Instal paket", "Perbarui semua paket terinstal", "Hapus paket", "Cari nama dan ringkasan paket", "List paket terinstal atau tersedia", "Tampilkan detail paket"], n: ["Instal sebuah paket", "Perbarui semuanya", "Cari ringkasan", "Detail paket"], s: ["Sukses", "Terjadi kesalahan"] },
  dnf: { d: "Manajer paket generasi berikutnya untuk Fedora/RHEL 8+.", d2: "Manajer paket generasi berikutnya untuk Fedora dan RHEL 8+, menggantikan yum dengan penyelesaian dependensi yang lebih baik dan sintaks perintah yang kompatibel.", o: ["Instal paket", "Perbarui semua paket terinstal", "Hapus paket", "Cari metadata paket", "Hapus paket dependensi yang tak diperlukan", "Query paket dari repositori"], n: ["Perbarui semua paket", "Instal sebuah paket", "Buang dependensi yang tak diperlukan", "Kasus: hitung paket terinstal"], s: ["Sukses", "Terjadi kesalahan"] },
  rpm: { d: "Manajer paket RPM untuk paket .rpm.", d2: "Manajer paket RPM level rendah: menginstal dan meng-query paket .rpm serta basis data RPM tanpa resolusi repositori atau dependensi.", o: ["Instal berkas paket", "Instal atau upgrade paket", "Query semua paket terinstal", "List berkas milik sebuah paket", "Cari paket pemilik sebuah berkas", "Hapus (uninstal) paket", "Verifikasi berkas paket terhadap basis data"], n: ["Paket terinstal yang cocok dengan bash", "Kasus: paket mana pemilik berkas ini?", "Upgrade atau instal", "Verifikasi berkas terhadap basis data"], s: ["Sukses", "Terjadi kesalahan"] },
  pacman: { d: "Manajer paket untuk Arch Linux.", d2: "Manajer paket Arch Linux: cepat, sederhana, dan konsisten, menyinkronkan dengan repositori remote dan membangun dari AUR lewat pembantu seperti yay.", o: ["Sinkronkan (instal) paket", "Segarkan basis data dan upgrade semua paket (ritual Arch)", "Hapus paket (-Rs juga membuang dependensi tak perlu)", "Cari di repositori", "Query info / daftar berkas paket terinstal"], n: ["Kasus: sinkronkan basis data dan upgrade semua (ritual Arch)", "Instal sebuah paket", "Cari di repositori", "Hapus beserta konfigurasi dan dependensi tak perlu"], s: ["Sukses", "Terjadi kesalahan"] },
  yay: { d: "Pembantu AUR dan pembungkus pacman untuk Arch Linux.", d2: "Pembantu AUR untuk Arch Linux yang membungkus pacman dan makepkg: mencari dan menginstal paket dari Arch User Repository dengan resolusi dependensi.", o: ["Instal dari repositori atau AUR", "Upgrade semuanya, termasuk paket AUR", "Cari di repositori resmi dan AUR sekaligus", "Hapus paket beserta konfigurasi dan dependensinya"], n: ["Instal dari AUR", "Upgrade paket resmi dan AUR", "Kasus: cari di repositori dan AUR bersamaan"], s: ["Sukses", "Terjadi kesalahan"] },
  zypper: { d: "Manajer paket untuk openSUSE/SUSE.", d2: "Manajer paket openSUSE dan SUSE Linux, dengan manajemen repositori, resolusi dependensi, dan antarmuka yang dapat diskripkan.", o: ["Instal paket", "Segarkan semua metadata repositori", "Perbarui paket terinstal", "Cari paket", "Hapus paket", "List repositori yang dikonfigurasi"], n: ["Instal sebuah paket", "Segarkan, lalu perbarui", "Kasus: cari semua paket kernel"], s: ["Sukses", "Terjadi kesalahan"] },
  apk: { d: "Manajer paket untuk Alpine Linux.", d2: "Manajer paket ringan Alpine Linux, dikenal karena image mungil dan operasi cepat; bawaan di sebagian besar container minimal.", o: ["Instal paket", "Hapus paket", "Segarkan indeks repositori", "Upgrade semua paket terinstal", "Cari paket yang tersedia", "Tampilkan informasi paket"], n: ["Instal sebuah paket", "Segarkan dan upgrade", "Pencarian verbose"], s: ["Sukses", "Terjadi kesalahan"] },
  snap: { d: "Menginstal dan mengelola paket snap (Ubuntu).", d2: "Menginstal dan mengelola paket snap — bundel aplikasi mandiri yang memperbarui diri dari Snap Store, di-sandbox oleh AppArmor.", o: ["Instal snap (--classic untuk tanpa pembatasan)", "List snap terinstal", "Hapus snap", "Segarkan (perbarui) semua snap terinstal", "Cari di store"], n: ["Kasus: instal VS Code dengan akses sistem penuh", "Snap terinstal", "Perbarui semua snap"], s: ["Sukses", "Terjadi kesalahan"] },
  flatpak: { d: "Menginstal dan mengelola aplikasi Flatpak yang di-sandbox.", d2: "Menginstal dan menjalankan aplikasi desktop ber-sandbox dengan runtime sendiri, kebanyakan dari repositori Flathub.", o: ["Instal aplikasi, mis. flathub org.gimp.GIMP", "List aplikasi dan runtime terinstal", "Jalankan aplikasi terinstal", "Perbarui aplikasi dan runtime terinstal", "Hapus aplikasi"], n: ["Instal GIMP dari Flathub", "Aplikasi dan runtime terinstal", "Perbarui semuanya"], s: ["Sukses", "Terjadi kesalahan"] },
  pip: { d: "Penginstal paket Python.", d2: "Penginstal paket Python: menginstal pustaka dari PyPI ke site-packages (atau virtual environment, yang merupakan praktik yang disarankan).", o: ["Instal paket dari PyPI", "Instal dari berkas requirements.txt", "List paket terinstal (freeze = format requirements)", "Hapus paket", "Tampilkan informasi tentang paket terinstal"], n: ["Instal dari PyPI", "Instal dependensi sebuah proyek", "Kasus: pin lingkungan saat ini", "Instal per-pengguna tanpa root"], s: ["Sukses", "Terjadi kesalahan"], v: ["Virtual environment aktif; pip menginstal ke dalamnya", "Lokasi berkas konfigurasi pip", "Opsi long apa pun dapat diset, mis. PIP_REQUIRE_VIRTUALENV=1"] },
  npm: { d: "Manajer paket Node.js.", d2: "Manajer paket Node.js: menginstal pustaka dari registry npm ke node_modules dan menjalankan skrip proyek yang didefinisikan di package.json.", o: ["Instal dependensi (atau paket tertentu)", "Instal paket secara global", "Jalankan skrip dari package.json, mis. npm run build", "Hapus paket", "List paket terinstal"], n: ["Tambah dependensi", "Jalankan skrip package.json", "Perkakas CLI global", "Kasus: instal bersih dari lockfile (CI)"], s: ["Sukses", "Terjadi kesalahan"], v: ["Label lingkungan yang dibaca banyak paket (mis. production)", "Konfigurasi npm apa pun sebagai variabel env, mis. NPM_CONFIG_PREFIX, NPM_CONFIG_REGISTRY"] },
  gem: { d: "Manajer paket RubyGems untuk Ruby.", d2: "Mengelola Ruby gem — paket-paket ekosistem Ruby — menginstalnya dari RubyGems.org.", o: ["Instal gem", "List gem terinstal", "Hapus gem", "Perbarui gem terinstal", "Cari gem remote"], n: ["Instal sebuah gem", "Gem terinstal", "Perbarui semua gem"], s: ["Sukses", "Terjadi kesalahan"] },
  cargo: { d: "Manajer paket dan perkakas build Rust.", d2: "Sistem build dan manajer paket toolchain Rust: membuat proyek, menyelesaikan crate dari crates.io, membangun, menguji, dan merilisnya.", o: ["Buat proyek baru / inisialisasi di sini", "Kompilasi proyek (--release untuk teroptimasi)", "Bangun dan jalankan proyek", "Jalankan pengujian proyek", "Tambah dependensi ke Cargo.toml"], n: ["Scaffold proyek baru", "Build teroptimasi", "Jalankan suite pengujian", "Kasus: tambah crate dependensi"], s: ["Sukses", "Terjadi kesalahan"], v: ["Direktori untuk cache dan biner terinstal cargo (bawaan ~/.cargo)", "Direktori untuk artefak build alih-alih ./target", "Direktori untuk toolchain rustup"] }
});

Object.assign(window.IDTXT, {
  pgrep: { d: "Cari ID proses berdasarkan nama atau atribut lain.", d2: "Mencari ID proses yang namanya (atau baris perintah penuh dengan -f) cocok dengan sebuah pola, lalu mencetak PID-nya — paruh query dari pkill.", o: ["List baris perintah lengkap sekaligus PID-nya", "Cocokkan terhadap baris perintah penuh", "List nama proses sekaligus PID-nya", "Cocokkan hanya proses milik pengguna tertentu", "Cocokkan nama proses secara persis"], n: ["PID plus baris perintah", "Cocokkan baris perintah penuh", "Kasus: hitung proses yang cocok"], s: ["Satu atau lebih proses cocok", "Tidak ada proses yang cocok", "Syntax error pada baris perintah", "Error fatal"] }
});
